module.exports = [
    "[ chitbuzz ]~8 7 21 23 22 66 68 67 201 ?|203",
    "[ chitbuzz ]~start with 'w' (ewak)|wake",
    "[ chitbuzz ]~start with 'c' (acb)|cab",
    "[ chitbuzz ]~8 6 3 ? 4 1 4|6",
    "[ chitbuzz ]~start with 'n' (etnx)|next",
    "[ chitbuzz ]~start with 'e' (gge)|egg",
    "[ chitbuzz ]~start with 'd' (deos)|dose",
    "[ chitbuzz ]~start with 'p' (pchit)|pitch",
    "[ chitbuzz ]~start with 'o' (on)|on",
    "[ chitbuzz ]~start with 'c' (ocdwr)|crowd",
    "[ chitbuzz ]~start with 'i' (rion)|iron",
    "[ chitbuzz ]~4 2 6 9 7 21 ? 22 66 69|24",
    "[ chitbuzz ]~start with 'p' (rkpo)|pork",
    "[ chitbuzz ]~start with 'c' (hcouc)|couch",
    "[ chitbuzz ]~start with 't' (otw)|two",
    "[ chitbuzz ]~9 8 9 11 10 ? 13|11",
    "[ chitbuzz ]~start with 'f' (fork)|fork",
    "[ chitbuzz ]~start with 'k' (tki)|kit",
    "math~? - 1 = 1|2",
    "[ chitbuzz ]~start with 's' (nski)|skin",
    "[ chitbuzz ]~start with 'b' (ubt)|but",
    "[ chitbuzz ]~start with 'm' (amde)|made",
    "[ chitbuzz ]~start with 'h' (lafh)|half",
    "[ chitbuzz ]~start with 'b' (rbief)|brief",
    "[ chitbuzz ]~start with 'r' (erahc)|reach",
    "[ chitbuzz ]~start with 'w' (iwne)|wine",
    "[ chitbuzz ]~start with 'e' (alequ)|equal",
    "[ chitbuzz ]~start with 'k' (eyk)|key",
    "[ chitbuzz ]~5 5 7 ? 5 7 5|5",
    "[ chitbuzz ]~start with 's' (parsk)|spark",
    "[ chitbuzz ]~start with 't' (ytpe)|type",
    "[ chitbuzz ]~start with 'l' (pli)|lip",
    "[ chitbuzz ]~start with 'h' (llah)|hall",
    "[ chitbuzz ]~start with 'w' (wnet)|went",
    "math~4 x 3 = ?|12",
    "[ chitbuzz ]~start with 'b' (kobo)|book",
    "[ chitbuzz ]~start with 'c' (htlco)|cloth",
    "[ chitbuzz ]~4 ? 8 11 9 36 39 37 148 151|2",
    "[ chitbuzz ]~start with 'm' (man)|man",
    "[ chitbuzz ]~6 12 10 7 14 12 9 18 ? 13|16",
    "[ chitbuzz ]~start with 'g' (ogod)|good",
    "[ chitbuzz ]~start with 'b' (aber)|bear",
    "[ chitbuzz ]~9 13 14 11 15 16 13 17 18 ?|15",
    "[ chitbuzz ]~start with 'w' (yaw)|way",
    "[ chitbuzz ]~start with 'b' (ayb)|bay",
    "math~5กา1=?|5",
    "[ chitbuzz ]~start with 't' (ahtt)|that",
    "math~1 + ? x 4 = 8|1",
    "math~8กา4=?|2",
    "[ chitbuzz ]~start with 'c' (wlca)|claw",
    "[ chitbuzz ]~start with 'm' (emer)|mere",
    "[ chitbuzz ]~start with 'n' (onen)|none",
    "[ chitbuzz ]~start with 'r' (ursh)|rush",
    "[ chitbuzz ]~start with 'w' (ewaht)|wheat",
    "math~? / 1 = 6|6",
    "[ chitbuzz ] Start With 'q' ~ { zqiu } |[ chitbuzz ]",
    "[MATHS] ~ 3 - 4 + 1 = ? |0",
    "[ chitbuzz ] Start With 'm' ~ { otumn } |mount",
    "[ chitbuzz ] Start With 'b' ~ { yb } |by",
    "[ chitbuzz ] Start With 'g' ~ { _o } |go",
    "[ chitbuzz ] Start With 'q' ~ { qitu } |quit",
    "[ chitbuzz ] Start With 'l' ~ { lvoe } |love",
    "[ chitbuzz ] Start With 't' ~ { tlal } |tall",
    "[ chitbuzz ] Start With 'h' ~ { hryru } |hurry",
    "[MATHS] ~ 6 / 10 + 5 x 15 = ?|84",
    "[ chitbuzz ] Start With 'd' ~ { droo } |door",
    "[ chitbuzz ] Start With 'e' ~ { eitd } |edit",
    "[ chitbuzz ] Start With 'd' ~ { _ar__e_s } |darkness",
    "[ chitbuzz ] Start With 'f' ~ { _r__nd } |friend",
    "[ chitbuzz ] Start With 's' ~ { eupsr } |super",
    "[ chitbuzz ] Start With 'h' ~ { __nd_ } |hindi",
    "[ chitbuzz ] Start With 's' ~ { su_er_an } |superman",
    "[MATHS] ~ 9 / 9 + 4 x 8 = ?|40",
    "[ chitbuzz ] Start With 'k' ~ { k_ral_ } |kerala",
    "[ chitbuzz ] Start With 't' ~ { t_m_l } |tamil",
    "[ chitbuzz ] Start With 'm' ~ { m_la_a_am } |malayalam",
    "[ chitbuzz ] Start With 'i' ~ { in_i_ } |india",
    "[ chitbuzz ] Start With 'a' ~ { _m_ri_a } |america",
    "[ chitbuzz ] Start With 'j' ~ { j_p_n } |japan",
    "[MATHS] ~ ? x 18 - 3 - 13 = 56|4",
    "[ chitbuzz ] Start With 'e' ~ { e_g_an_ } |england",
    "[ chitbuzz ] Start With 'n' ~ { elpan } |nepal",
    "[ chitbuzz ] Start With 'p' ~ { pniskata } |pakistan",
    "[ chitbuzz ] Start With 'b' ~ { deb } |bed",
    "[ chitbuzz ] Start With 'r' ~ { re_ } |red",
    "[ chitbuzz ] Start With 'n' ~ { ___buz_ } |nimbuzz",
    "[MATHS] ~ 4 x 7 - ? = 10|18",
    "[ chitbuzz ] Start With 'f' ~ { f_c_b__k } |facebook",
    "[ chitbuzz ] Start With 'm' ~ { elbmoi } |mobile",
    "[ chitbuzz ] Start With 'p' ~ { onhep } |phone",
    "[ chitbuzz ] Start With 's' ~ { ocsoret } |scooter",
    "[ chitbuzz ] Start With 's' ~ { usepr } |super",
    "[MATHS] ~ ? x 8 / 2 + 6 = 22|4",
    "[ chitbuzz ] Start With 'a' ~ { _m_zi__l_ } |amazingly",
    "[ chitbuzz ] Start With 'f' ~ { tfas } |fast",
    "[ chitbuzz ] Start With 'j' ~ { upmj } |jump",
    "[ chitbuzz ] Start With 'r' ~ { rtkeco } |rocket",
    "[ chitbuzz ] Start With 'p' ~ { p_w_r } |power",
    "[ chitbuzz ] Start With 's' ~ { rsta } |star",
    "[ chitbuzz ] Start With 'm' ~ { m_l_ip_r_os_ } |multipurpose",
    "[MATHS] ~ 17 / 2 x 6 + ? = 60|9",
    "[ chitbuzz ] Start With 'r' ~ { aylor } |royal",
    "[ chitbuzz ] Start With 'o' ~ { iaclfofi } |official",
    "[ chitbuzz ] Start With 'c' ~ { c_nf_s_n_ } |confusing",
    "[ chitbuzz ] Start With 'c' ~ { com_l_x } |complex",
    "[ chitbuzz ] Start With 'f' ~ { erfi } |fire",
    "[ chitbuzz ] Start With 'l' ~ { eaevl } |leave",
    "[MATHS] ~ 4 x 8 / ? - 6 = 10|2",
    "[ chitbuzz ] Start With 'i' ~ { i_d_a } |india",
    "[ chitbuzz ] Start With 's' ~ { s_yl_ } |style",
    "[ chitbuzz ] Start With 'l' ~ { ezral } |lazer",
    "[ chitbuzz ] Start With 'p' ~ { torp } |port",
    "[ chitbuzz ] Start With 'd' ~ { d_ng_r } |danger",
    "[MATHS] ~ 3 + ? + 17 = 27|7",
    "[ chitbuzz ] Start With 'g' ~ { ge_tle__n } |gentleman",
    "[ chitbuzz ] Start With 's' ~ { otsyr } |story",
    "[ chitbuzz ] Start With 's' ~ { ssortp } |sports",
    "[ chitbuzz ] Start With 'c' ~ { cclko } |clock",
    "[ chitbuzz ] Start With 'd' ~ { yldaisp } |display",
    "[MATHS] ~ 14 - 18 - 2 + 16 = ?|10",
    "[ chitbuzz ] Start With 'i' ~ { aedi } |idea",
    "[ chitbuzz ] Start With 's' ~ { elplsgni } |spelling",
    "[ chitbuzz ] Start With 't' ~ { unrt } |turn",
    "[ chitbuzz ] Start With 'b' ~ { ecalban } |balance",
    "[ chitbuzz ] Start With 'a' ~ { amair } |aamir",
    "[MATHS] ~ 7 / 2 + 6 x ? = 95|10",
    "[ chitbuzz ] Start With 'c' ~ { c_m_ra } |camera",
    "[ chitbuzz ] Start With 'b' ~ { b_i_d_ng } |building",
    "[ chitbuzz ] Start With 'c' ~ { c_ee_e } |cheese",
    "[ chitbuzz ] Start With 'b' ~ { b_s__ess } |business",
    "[ chitbuzz ] Start With 'c' ~ { c_m_lex } |complex",
    "[MATHS] ~ 6 + 10 - 2 = ?|14",
    "[ chitbuzz ] Start With 'd' ~ { d_ug_t_r } |daughter",
    "[ chitbuzz ] Start With 'b' ~ { tsbe } |best",
    "[ chitbuzz ] Start With 'c' ~ { co_n_ry } |country",
    "[ chitbuzz ] Start With 'd' ~ { d__vi_g } |driving",
    "[ chitbuzz ] Start With 'e' ~ { e_u_a_t_on } |education",
    "[MATHS] ~ ? - 10 + 14 x 5 = 50|6",
    "[ chitbuzz ] Start With 'f' ~ { f_m_ly} |family",
    "[ chitbuzz ] Start With 'f' ~ { f_m_l_ } |female",
    "[ chitbuzz ] Start With 'f' ~ { isfh } |fish",
    "[ chitbuzz ] Start With 'g' ~ { _i_l } |girl",
    "[MATHS] ~ 12 + 16 - 10 / 2 = ?|9",
    "[ chitbuzz ] Start With 'h' ~ { h_p_y } |happy",
    "[ chitbuzz ] Start With 'h' ~ { h_s_o_y } |history",
    "[ chitbuzz ] Start With 'i' ~ { i_st_u_et } |instrument",
    "[ chitbuzz ] Start With 'l' ~ { l_n_u_ge } |language",
    "[MATHS] ~ 14 + 15 - ? + 13 = 32|10",
    "[ chitbuzz ] Start With 'j' ~ { j_u_n_y } |journey",
    "[ chitbuzz ] Start With 'k' ~ { k_if_ } |knife",
    "[ chitbuzz ] Start With 'l' ~ { l_v_ } |love",
    "[ chitbuzz ] Start With 'm' ~ { __c_ine } |machine",
    "[MATHS] ~ 4 + 17 - 9 = ?|12",
    "[ chitbuzz ] Start With 'l' ~ { __t_er } |letter",
    "[ chitbuzz ] Start With 'm' ~ { m_r_i_d } |married",
    "[ chitbuzz ] Start With 'n' ~ { n_t_r_l } |natural",
    "[MATHS] ~ 12 + 6 x ? = 180|10",
    "[ chitbuzz ] Start With 'm' ~ { m_rn__g } |morning",
    "[ chitbuzz ] Start With 'n' ~ { ne_e_s_ry } |necessary",
    "[ chitbuzz ] Start With 'o' ~ { o_f_c_r } |officer",
    "[ chitbuzz ] Start With 'p' ~ { p_p_r } |paper",
    "[MATHS] ~ 3 x ? x 11 - 2 = 229|7",
    "[ chitbuzz ] Start With 'o' ~ { o_n_r } |owner",
    "[ chitbuzz ] Start With 'p' ~ { p_t_t_ } |potato",
    "[ chitbuzz ] Start With 'q' ~ { q_a_i_y } |quality",
    "[ chitbuzz ] Start With 'a' ~ { a_i } |ali",
    "[MATHS] ~ ? x 8 - 2 = 30|4",
    "[ chitbuzz ] Start With 'q' ~ { q_e_t_on } |question",
    "[ chitbuzz ] Start With 'r' ~ { r_v_r } |river",
    "[ chitbuzz ] Start With 's' ~ { enciesc } |science",
    "[ chitbuzz ] Start With 's' ~ { s_r_ous } |serious",
    "[ chitbuzz ] Start With 's' ~ { gons } |song",
    "[MATHS] ~ 3 x 13 = ?|39",
    "[ chitbuzz ] Start With 't' ~ { ktitce } |ticket",
    "[ chitbuzz ] Start With 's' ~ { sy__em } |system",
    "[ chitbuzz ] Start With 't' ~ { tr_n_po_t } |transport",
    "[ chitbuzz ] Start With 'u' ~ { um__e_la } |umbrella",
    "[MATHS] ~ 14 - 18 - 12 + ? = 0|16",
    "[ chitbuzz ] Start With 'w' ~ { w_at_er } |weather",
    "[ chitbuzz ] Start With 'w' ~ { w_nd_w } |window",
    "[ chitbuzz ] Start With 'y' ~ { ye_l_w } |yellow",
    "[ chitbuzz ] Start With 'y' ~ { y_s } |yes",
    "[MATHS] ~ 8 / ? x 3 = 8|3",
    "[ chitbuzz ] Start With 'h' ~ { eraht } |heart",
    "[ chitbuzz ] Start With 's' ~ { rstat } |smart",
    "[ chitbuzz ] Start With 'i' ~ { in_e_lig_n_ } |intelligent",
    "[ chitbuzz ] Start With 'n' ~ { cien } |nice",
    "[MATHS] ~ ? - 19 = 0|19",
    "[ chitbuzz ] Start With 'g' ~ { __ng_t_r } |gangster",
    "[ chitbuzz ] Start With 'c' ~ { c_ri_g } |caring",
    "[ chitbuzz ] Start With 'd' ~ { d_s_i_g } |dashing",
    "[ chitbuzz ] Start With 'a' ~ { a_or_b_e } |adorable",
    "[MATHS] ~ 3 x 6 / 1 + ? = 23|5",
    "[ chitbuzz ] Start With 'm' ~ { m_rv_lo_s } |marvelous",
    "[ chitbuzz ] Start With 'a' ~ { at_ra_ti_e } |attractive",
    "[ chitbuzz ] Start With 'f' ~ { _r_en_ly } |friendly",
    "[ chitbuzz ] Start With 'l' ~ { l_v_ly } |lovely",
    "[MATHS] ~ 3 x 7 / 1 + 5 = ?|26",
    "[ chitbuzz ] Start With 'a' ~ { a_t_t_de } |attitude",
    "[ chitbuzz ] Start With 'f' ~ { f_i_h_ul } |faithful",
    "[ chitbuzz ] Start With 'a' ~ { a_bi_ious } |ambitious",
    "[ chitbuzz ] Start With 's' ~ { s_n_i_ive } ||sensitive",
    "[MATHS] ~ 16 - 10 / 2 = ?|3",
    "[ chitbuzz ] Start With 's' ~ { s__ent } |silent",
    "[ chitbuzz ] Start With 'r' ~ { r_spo_s_ble } |responsible",
    "[ chitbuzz ] Start With 'e' ~ { e_ce_l_nt } |excellent",
    "[ chitbuzz ] Start With 'c' ~ { c_arm_n_ } |charming",
    "[ chitbuzz ] Start With 'd' ~ { _a_zli_g } |dazzling",
    "[MATHS] ~ 10 + 14 - 9 - 12 = ?|3",
    "[ chitbuzz ] Start With 'e' ~ { e_ega_t } |elegant",
    "[ chitbuzz ] Start With 'f' ~ { f_n_as_ic } |fantastic",
    "[ chitbuzz ] Start With 'i' ~ { laeid } |ideal",
    "[ chitbuzz ] Start With 'n' ~ { n_u_h_y } |naughty",
    "[MATHS] ~ 15 + 7 = ?|22",
    "[ chitbuzz ] Start With 'u' ~ { u_i_ue } |unique",
    "[ chitbuzz ] Start With 'w' ~ { w_nd_r_ul } |wonderful",
    "[ chitbuzz ] Start With 'g' ~ { g_am_r_us } |glamorous",
    "[ chitbuzz ] Start With 's' ~ { s_d_c_ive } |seductive",
    "[MATHS] ~ ? / 12 x 3 = 2|8",
    "[ chitbuzz ] Start With 's' ~ { sp_r_li_g } |sparkling",
    "[ chitbuzz ] Start With 's' ~ { sh_ni_g } |shining",
    "[ chitbuzz ] Start With 'e' ~ { en_rge_i_ } |energetic",
    "[ chitbuzz ] Start With 's' ~ { su_e_b } |superb",
    "[MATHS] ~ 16 - 1 - ? = 10|5",
    "[ chitbuzz ] Start With 't' ~ { _hr_e } |three",
    "[ chitbuzz ] Start With 'e' ~ { e_d } |end",
    "[ chitbuzz ] Start With 'l' ~ { la_t_p } |laptop",
    "[ chitbuzz ] Start With 'j' ~ { _a_n } |jaan",
    "[ chitbuzz ] Start With 's' ~ { _w_et } |sweet",
    "[MATHS] ~ 2 x 6 + 10 - ? = 21|1",
    "[ chitbuzz ] Start With 'b' ~ { _las_ } |blast",
    "[ chitbuzz ] Start With 'l' ~ { o_l } |owl",
    "[ chitbuzz ] Start With 'r' ~ { r_gr_t } |regret",
    "[ chitbuzz ] Start With 'h' ~ { _i_h } |high",
    "[ chitbuzz ] Start With 'm' ~ { m_n } |man",
    "[MATHS] ~ 1 - 12 + 16 = ?|5",
    "[ chitbuzz ] Start With 'g' ~ { _en_l_ } |gentle",
    "[ chitbuzz ] Start With 'l' ~ { l_op } |loop",
    "[ chitbuzz ] Start With 'k' ~ { ki_le_ } |killer",
    "[ chitbuzz ] Start With 'l' ~ { __me } |lime",
    "[MATHS] ~ ? - 5 = 6|11",
    "[ chitbuzz ] Start With 'm' ~ { _inis__r } |minister",
    "[ chitbuzz ] Start With 'n' ~ { no_th } |north",
    "[ chitbuzz ] Start With 'o' ~ { _n_ } |one",
    "[ chitbuzz ] Start With 'p' ~ { p_w_r } |power",
    "[MATHS] ~ 12 / ? + 7 = 8|12",
    "[ chitbuzz ] Start With 'q' ~ { qu_r_er } |quarter",
    "[ chitbuzz ] Start With 'r' ~ { r_p_ } |rape",
    "[ chitbuzz ] Start With 's' ~ { s_ng_r } |singer",
    "[MATHS] ~ ? + 4 x 15 = 210|10",
    "[ chitbuzz ] Start With 't' ~ { tw__ty } |twenty",
    "[ chitbuzz ] Start With 's' ~ { s__g } |sing",
    "[ chitbuzz ] Start With 'w' ~ { __n } |win",
    "[ chitbuzz ] Start With 'y' ~ { yo_t_ } |youth",
    "[MATHS] ~ 1 x 5 + 16 = ?|21",
    "[ chitbuzz ] Start With 'u' ~ { lcenu } |uncle",
    "[ chitbuzz ] Start With 'v' ~ { v__w } |view",
    "[ chitbuzz ] Start With 'v' ~ { vi__er } |viewer",
    "[ chitbuzz ] Start With 'z' ~ { igzn } |zing",
    "[MATHS] ~ 6 + 16 - ? = 11|11",
    "[ chitbuzz ] Start With 's' ~ { isgn } |sing",
    "[ chitbuzz ] Start With 'b' ~ { igbn } |bing",
    "[ chitbuzz ] Start With 'k' ~ { nikg } |king",
    "[ chitbuzz ] Start With 'w' ~ { giwn } |wing",
    "[MATHS] ~ ? / 9 = 1|9",
    "[ chitbuzz ] Start With 'p' ~ { nigp } |ping",
    "[ chitbuzz ] Start With 'a' ~ { utboa } |about",
    "[ chitbuzz ] Start With 'b' ~ { __t } |bat",
    "[ chitbuzz ] Start With 'b' ~ { _al_ } |ball",
    "[MATHS] ~ 13 + 5 / ? = 2|9",
    "[ chitbuzz ] Start With 'b' ~ { _i_l } |bill",
    "[ chitbuzz ] Start With 'b' ~ { onrb } |born",
    "[ chitbuzz ] Start With 'b' ~ { __t } |bot",
    "[ chitbuzz ] Start With 'b' ~ { __n } |ban",
    "[MATHS] ~ 3 x 3 = ?|9",
    "[ chitbuzz ] Start With 'b' ~ { _en } |ben",
    "[ chitbuzz ] Start With 'b' ~ { anaban } |banana",
    "[ chitbuzz ] Start With 'b' ~ { tubret } |butter",
    "[ chitbuzz ] Start With 'b' ~ { _u_ } |but",
    "[MATHS] ~ ? - 1 - 11 = 4|16",
    "[ chitbuzz ] Start With 'b' ~ { tbi } |bit",
    "[ chitbuzz ] Start With 'b' ~ { iteb } |bite",
    "[ chitbuzz ] Start With 'b' ~ { boto } |boot",
    "[ chitbuzz ] Start With 'b' ~ { __r } |bar",
    "[MATHS] ~ 13 + ? + 8 = 35|14",
    "[ chitbuzz ] Start With 'b' ~ { rbbrea } |barber",
    "[ chitbuzz ] Start With 'b' ~ { b__ter } |better",
    "[ chitbuzz ] Start With 'b' ~ { ebt } |bet",
    "[MATHS] ~ ? - 9 + 13 + 17 = 39|18",
    "[ chitbuzz ] Start With 'b' ~ { ebaevh } |behave",
    "[ chitbuzz ] Start With 'b' ~ { ebidhn } |behind",
    "[ chitbuzz ] Start With 'b' ~ { ubnr } |burn",
    "[ chitbuzz ] Start With 'b' ~ { owlb } |blow",
    "[MATHS] ~ 7 x 8 / 2 = ?|28",
    "[ chitbuzz ] Start With 'b' ~ { __wl } |bowl",
    "[ chitbuzz ] Start With 'b' ~ { __wl_ng } |bowling",
    "[ chitbuzz ] Start With 'b' ~ { otpho } |photo",
    "[ chitbuzz ] Start With 'c' ~ { c_t } |cat",
    "[ chitbuzz ] Start With 'c' ~ { c_w } |cow",
    "[MATHS] ~ 15 - 9 x ? = 78|13",
    "[ chitbuzz ] Start With 'c' ~ { __r } |car",
    "[ chitbuzz ] Start With 'c' ~ { __cl_ } |cycle",
    "[ chitbuzz ] Start With 'c' ~ { alwc } |claw",
    "[MATHS] ~ math~? + 14 x 5 = 120|10",
    "[ chitbuzz ] Start With 'c' ~ { __ll } |call",
    "[ chitbuzz ] Start With 'c' ~ { _e_l } |cell",
    "[ chitbuzz ] Start With 'c' ~ { __n } |can",
    "[ chitbuzz ] Start With 'c' ~ { poc } |cop",
    "[MATHS] ~ 10 / ? = 5|2",
    "[ chitbuzz ] Start With 'c' ~ { __py } |copy",
    "[ chitbuzz ] Start With 'c' ~ { opepcr } |copper",
    "[ chitbuzz ] Start With 'c' ~ { __rd } |card",
    "[ chitbuzz ] Start With 'c' ~ { hsca } |cash",
    "[ chitbuzz ] Start With 'c' ~ { __t } |cot",
    "[MATHS] ~ 2 - ? + 17 = 13|6",
    "[ chitbuzz ] Start With 'c' ~ { c__ck } |clock",
    "[ chitbuzz ] Start With 'c' ~ { ilkcc } |click",
    "[ chitbuzz ] Start With 'c' ~ { cr__k } |crack",
    "[ chitbuzz ] Start With 'c' ~ { cr__ker } |cracker",
    "[ chitbuzz ] Start With 'c' ~ { troc } |cort",
    "[MATHS] ~ 11 + 14 + ? = 43|18",
    "[ chitbuzz ] Start With 'c' ~ { cpam } |camp",
    "[ chitbuzz ] Start With 'c' ~ { __mb } |camb",
    "[ chitbuzz ] Start With 'c' ~ { _r_wn } |crown",
    "[ chitbuzz ] Start With 'c' ~ { ahcn } |chan",
    "[ chitbuzz ] Start With 'c' ~ { _h_in } |chain",
    "[MATHS] ~ 10 / ? = 1|10",
    "[ chitbuzz ] Start With 'c' ~ { _hi_a } |china",
    "[ chitbuzz ] Start With 'c' ~ { __at } |chat",
    "[ chitbuzz ] Start With 'c' ~ { c__tro_m } |chatroom",
    "[ chitbuzz ] Start With 'c' ~ { _h_t_r } |chater",
    "[MATHS] ~ ? + 7 x 10 = 190|12",
    "[ chitbuzz ] Start With 'c' ~ { _han_e } |change",
    "[ chitbuzz ] Start With 'c' ~ { ionc } |coin",
    "[ chitbuzz ] Start With 'c' ~ { cot__n } |cotton",
    "[ chitbuzz ] Start With 'c' ~ { utctre } |cutter",
    "[[ chitbuzz ]] ~ 4 1 3 ? 2 6 8|5",
    "[ chitbuzz ] Start With 'd' ~ { __t } |dot",
    "[ chitbuzz ] Start With 'd' ~ { rodo } |door",
    "[ chitbuzz ] Start With 'd' ~ { __m } |dam",
    "[ chitbuzz ] Start With 'd' ~ { rudm } |drum",
    "[MATHS] ~ 9 + ? + 4 = 26|13",
    "[ chitbuzz ] Start With 'd' ~ { d_n } |don",
    "[ chitbuzz ] Start With 'd' ~ { ldol } |doll",
    "[ chitbuzz ] Start With 'd' ~ { dea_h } |death",
    "[ chitbuzz ] Start With 'd' ~ { aded } |dead",
    "[MATHS] ~ 7 + ? - 12 = 12|17",
    "[ chitbuzz ] Start With 'd' ~ { erda } |dear",
    "[ chitbuzz ] Start With 'd' ~ { _oc_or } |doctor",
    "[ chitbuzz ] Start With 'd' ~ { __ugh_er } |daughter",
    "[ chitbuzz ] Start With 'd' ~ { eivdr } |drive",
    "[MATHS] ~ 11 - 2 x 6 / 1 = ?|54",
    "[ chitbuzz ] Start With 'd' ~ { __iv_r } |driver",
    "[ chitbuzz ] Start With 'd' ~ { dr_v_ng } |driving",
    "[ chitbuzz ] Start With 'd' ~ { __rlin_ } |darling",
    "[ chitbuzz ] Start With 'd' ~ { adhs } |dash",
    "[ chitbuzz ] Start With 'd' ~ { idhs } |dish",
    "[MATHS] ~ 18 - ? + 13 = 29|2",
    "[ chitbuzz ] Start With 'd' ~ { __nn_r } |dinner",
    "[ chitbuzz ] Start With 'd' ~ { urgd } |drug",
    "[ chitbuzz ] Start With 'd' ~ { argd } |drag",
    "[MATHS] ~ 10 x 13 + ? = 135|5",
    "[ chitbuzz ] Start With 'd' ~ { edwr } |drew",
    "[ chitbuzz ] Start With 'd' ~ { word } |drow",
    "[ chitbuzz ] Start With 'd' ~ { __te } |date",
    "[ chitbuzz ] Start With 'd' ~ { cukd } |duck",
    "[MATHS] ~ 6 x 17 - ? x 5 = 500|2",
    "[ chitbuzz ] Start With 'd' ~ { dh_ni } |dhoni",
    "[ chitbuzz ] Start With 'e' ~ { __r } |ear",
    "[ chitbuzz ] Start With 'e' ~ { ea_ } |eat",
    "[ chitbuzz ] Start With 'e' ~ { ea_n } |earn",
    "[MATHS] ~ ? + 7 - 11 / 2 = 4|12",
    "[ chitbuzz ] Start With 'e' ~ { _a_t } |east",
    "[ chitbuzz ] Start With 'e' ~ { _y_ } |eye",
    "[ chitbuzz ] Start With 'e' ~ { ey_s } |eyes",
    "[MATHS] ~ 9 + 13 + 16 - ? = 37|1",
    "[ chitbuzz ] Start With 'e' ~ { ey_b_ow } |eyebrow",
    "[ chitbuzz ] Start With 'e' ~ { __d } |end",
    "[ chitbuzz ] Start With 'e' ~ { _n_er } |enter",
    "[MATHS] ~ ? / 1 + 5 = 11|6",
    "[ chitbuzz ] Start With 'e' ~ { _ntr_ } |entry",
    "[ chitbuzz ] Start With 'e' ~ { _lbo_ } |elbow",
    "[ chitbuzz ] Start With 'e' ~ { _m_ } |emo",
    "[MATHS] ~ 6 x 7 / ? = 21|2",
    "[ chitbuzz ] Start With 'e' ~ { _mot_on } |emotion",
    "[ chitbuzz ] Start With 'e' ~ { en_rg_ } |energy",
    "[ chitbuzz ] Start With 'a' ~ { _l_ne } |alone",
    "[ chitbuzz ] Start With 'a' ~ { aayw } |away",
    "[MATHS] ~ 5 + 8 = ?|13",
    "[ chitbuzz ] Start With 'e' ~ { _qu_l } |equal",
    "[ chitbuzz ] Start With 'e' ~ { _xtr_ } |extra",
    "[ chitbuzz ] Start With 'e' ~ { __it } |exit",
    "[ chitbuzz ] Start With 'e' ~ { __ist } |exist",
    "[MATHS] ~ 1 - 1 x ? = 0|15",
    "[ chitbuzz ] Start With 'a' ~ { a_p_y } |apply",
    "[ chitbuzz ] Start With 'a' ~ { _pp_e } |apple",
    "[ chitbuzz ] Start With 'a' ~ { _u_ty } |aunty",
    "[MATHS] ~ 3 x 17 - 1 - ? = 38|12",
    "[ chitbuzz ] Start With 'e' ~ { _g_ } |egg",
    "[ chitbuzz ] Start With 'f' ~ { naf } |fan",
    "[ chitbuzz ] Start With 'f' ~ { atf } |fat",
    "[[ chitbuzz ]] ~ 4 4 8 9 ? 18 19|9",
    "[ chitbuzz ] Start With 'f' ~ { rfo } |for",
    "[ chitbuzz ] Start With 'f' ~ { uorf } |four",
    "[ chitbuzz ] Start With 'f' ~ { ievf } |five",
    "[MATHS] ~ 15 + 7 - 10 = ?|12",
    "[ chitbuzz ] Start With 'f' ~ { _i_th } |fifth",
    "[ chitbuzz ] Start With 'f' ~ { fif__en } |fifteen",
    "[ chitbuzz ] Start With 'f' ~ { _if_y } |fifty",
    "[MATHS] ~ 14 + ? - 9 = 20|15",
    "[ chitbuzz ] Start With 'f' ~ { f_ur_y } |fourty",
    "[ chitbuzz ] Start With 'f' ~ { ewf } |few",
    "[ chitbuzz ] Start With 'f' ~ { _ev_r } |fever",
    "[MATHS] ~ 1 x 4 + ? = 22|18",
    "[ chitbuzz ] Start With 'f' ~ { fo_l_w } |fellow",
    "[ chitbuzz ] Start With 'f' ~ { _ol__w_ng } |following",
    "[ chitbuzz ] Start With 'f' ~ { f_ld } |fold",
    "[ chitbuzz ] Start With 'f' ~ { __lm } |film",
    "[ chitbuzz ] Start With 'f' ~ { f_lm_d } |filmed",
    "[MATHS] ~ ? + 6 = 21|15",
    "[ chitbuzz ] Start With 'f' ~ { __ip } |flip",
    "[ chitbuzz ] Start With 'f' ~ { f_op } |flop",
    "[ chitbuzz ] Start With 'f' ~ { otlf } |flot",
    "[ chitbuzz ] Start With 'f' ~ { okrf } |fork",
    "[MATHS] ~ 10 + ? + 8 = 22|4",
    "[ chitbuzz ] Start With 'f' ~ { rogf } |frog",
    "[ chitbuzz ] Start With 'f' ~ { fi_ht } |fight",
    "[ chitbuzz ] Start With 'f' ~ { _i_hter } |fighter",
    "[ chitbuzz ] Start With 'f' ~ { saft } |fast",
    "[MATHS] ~ 10 + 14 + 8 - 12 = ?|20",
    "[ chitbuzz ] Start With 'f' ~ { _as_er } |faster",
    "[ chitbuzz ] Start With 'f' ~ { _ai_ous } |faimous",
    "[ chitbuzz ] Start With 'f' ~ { __i_nd } |friend",
    "[MATHS] ~ 15 - 19 - 4 + ? = 6|14",
    "[ chitbuzz ] Start With 'f' ~ { f__en_ly } |friendly",
    "[ chitbuzz ] Start With 'f' ~ { rfdo } |frod",
    "[ chitbuzz ] Start With 'f' ~ { eirf } |fire",
    "[ chitbuzz ] Start With 'f' ~ { edrif } |fired",
    "[MATHS] ~ 3 + 7 x 11 = ?|110",
    "[ chitbuzz ] Start With 'f' ~ { unf } |fun",
    "[ chitbuzz ] Start With 'f' ~ { lmaef } |flame",
    "[ chitbuzz ] Start With 'f' ~ { erifd } |fried",
    "[ chitbuzz ] Start With 'f' ~ { rfy } |fry",
    "[MATHS] ~ 6 + 1 - 2 x 15 = ?|75",
    "[ chitbuzz ] Start With 'b' ~ { eefb } |beef",
    "[ chitbuzz ] Start With 'b' ~ { eebr } |beer",
    "[ chitbuzz ] Start With 'b' ~ { rbb } |brb",
    "[ chitbuzz ] Start With 'b' ~ { nub } |bun",
    "[ chitbuzz ] Start With 'b' ~ { aerb } |bear",
    "[MATHS] ~ ? - 1 = 15|16",
    "[ chitbuzz ] Start With 'b' ~ { __t } |but",
    "[ chitbuzz ] Start With 'b' ~ { lbmea } |blame",
    "[ chitbuzz ] Start With 'b' ~ { arb } |bar",
    "[ chitbuzz ] Start With 'b' ~ { inbiiray } |biriyani",
    "[ chitbuzz ] Start With 't' ~ { ate } |tea",
    "[MATHS] ~ ? - 4 = 5|9",
    "[ chitbuzz ]~start with 's' (esnd)|send",
    "[ chitbuzz ]~start with 'p' (spat)|past",
    "[ chitbuzz ]~? 14 12 9 18 16 13|7",
    "math~6 / ? = 1|6",
    "[ chitbuzz ]~start with 't' (harts)|trash",
    "[ chitbuzz ]~8 9 11 22 23 25 ? 51 53 106|50",
    "[ chitbuzz ]~start with 'f' (efar)|fear",
    "[ chitbuzz ]~start with 'b' (iebrd)|bride",
    "[ chitbuzz ]~start with 'r' (rape)|rape",
    "[ chitbuzz ]~7 28 29 32 128 ? 132 528 529 532|129",
    "[ chitbuzz ]~start with 'a' (as)|as",
    "[ chitbuzz ]~start with 'c' (cear)|care",
    "math~1 x 4 = ?|4",
    "[ chitbuzz ]~start with 'p' (akpr)|park",
    "[ chitbuzz ]~start with 's' (ashll)|shall",
    "[ chitbuzz ]~start with 'b' (bssar)|brass",
    "[ chitbuzz ]~start with 's' (acsel)|scale",
    "[ chitbuzz ]~start with 'm' (aym)|may",
    "[ chitbuzz ]~1 ? 0 -4 -3 -5 -9 -8 -10 -14|2",
    "[ chitbuzz ]~4 ? 10 6 18 16 12 36 34 30|12",
    "[ chitbuzz ]~start with 'l' (gunl)|lung",
    "[ chitbuzz ]~start with 'h' (iher)|hire",
    "[ chitbuzz ]~start with 'm' (imx)|mix",
    "[ chitbuzz ]~start with 'c' (eavc)|cave",
    "[ chitbuzz ]~start with 'n' (now)|now",
    "[ chitbuzz ]~start with 'f' (fee)|fee",
    "[ chitbuzz ]~start with 'l' (vloe)|love",
    "[ chitbuzz ]~start with 't' (tstiw)|twist",
    "[ chitbuzz ]~start with 'e' (egg)|egg",
    "[ chitbuzz ]~start with 'r' (yolra)|royal",
    "[ chitbuzz ]~start with 'b' (abt)|bat",
    "[ chitbuzz ]~start with 't' (owtrh)|throw",
    "[ chitbuzz ]~start with 'g' (osge)|goes",
    "[ chitbuzz ]~start with 'n' (next)|next",
    "[ chitbuzz ]~start with 'a' (all)|all",
    "math~? x 4 = 20|5",
    "[ chitbuzz ]~start with 'o' (gouth)|ought",
    "[ chitbuzz ]~start with 'f' (feel)|feel",
    "[ chitbuzz ]~4 ? 8 4 5 8 4|5",
    "[ chitbuzz ]~start with 'n' (no)|no",
    "[ chitbuzz ]~start with 's' (easm)|same",
    "[ chitbuzz ]~start with 'u' (us)|us",
    "[ chitbuzz ]~start with 'g' (og)|go",
    "[ chitbuzz ]~8 10 7 21 23 20 60 62 59 ?|177",
    "[ chitbuzz ]~3 1 3 3 1 3 3 ? 3 3|1",
    "[ chitbuzz ]~start with 'p' (cp)|pc",
    "[ chitbuzz ]~start with 's' (wsim)|swim",
    "[ chitbuzz ]~start with 'c' (cypo)|copy",
    "[ chitbuzz ]~start with 'h' (mhoe)|home",
    "[ chitbuzz ]~start with 'l' (elmon)|lemon",
    "[ chitbuzz ]~start with 'd' (do)|do",
    "[ chitbuzz ]~start with 'd' (daed)|dead",
    "[ chitbuzz ]~start with 's' (ucsh)|such",
    "[ chitbuzz ]~start with 's' (teesh)|sheet",
    "[ chitbuzz ]~start with 'h' (hmeo)|home",
    "[ chitbuzz ]~start with 'a' (waaer)|aware",
    "[ chitbuzz ]~start with 'g' (gema)|game",
    "[ chitbuzz ]~start with 'b' (isbas)|basis",
    "[ chitbuzz ]~start with 'b' (aebhc)|beach",
    "[ chitbuzz ]~start with 'b' (eban)|bean",
    "[ chitbuzz ]~start with 'b' (lobw)|blow",
    "[ chitbuzz ]~start with 'f' (fair)|fair",
    "[ chitbuzz ]~3 0 0 4 ? 1 5 2 2 6|1",
    "[ chitbuzz ]~start with 'd' (epde)|deep",
    "math~7 / ? = 1|7",
    "[ chitbuzz ]~start with 'a' (acid)|acid",
    "[ chitbuzz ]~start with 'a' (ilaen)|alien",
    "[ chitbuzz ]~start with 'a' (icad)|acid",
    "[ chitbuzz ]~start with 'e' (aest)|east",
    "[ chitbuzz ]~start with 'l' (inlo)|lion",
    "[ chitbuzz ]~start with 'b' (stbao)|boast",
    "[ chitbuzz ]~start with 'p' (utp)|put",
    "[ chitbuzz ]~start with 't' (ortu)|tour",
    "[ chitbuzz ]~start with 's' (lepos)|slope",
    "[ chitbuzz ]~8 6 2 6 4 0 ? 2 -2 2|4",
    "math~9 + 3 = ?|12",
    "[ chitbuzz ]~start with 'p' (play)|play",
    "math~? x 3 = 27|9",
    "[ chitbuzz ]~start with 'c' (cook)|cook",
    "[ chitbuzz ]~start with 'd' (dish)|dish",
    "[ chitbuzz ]~3 9 13 11 33 37 ? 105 109 107|35",
    "[ chitbuzz ]~start with 'b' (boldn)|blond",
    "[ chitbuzz ]~start with 's' (zsie)|size",
    "[ chitbuzz ]~6 ? 11 8 16 15 12 24 23 20|12",
    "[ chitbuzz ]~start with 'c' (aphce)|cheap",
    "[ chitbuzz ]~start with 'g' (ogld)|gold",
    "[ chitbuzz ]~start with 'h' (ruoh)|hour",
    "[ chitbuzz ]~start with 'w' (wya)|way",
    "math~2 + 5 = ?|7",
    "[ chitbuzz ]~start with 'l' (orewl)|lower",
    "[ chitbuzz ]~start with 's' (erswa)|swear",
    "[ chitbuzz ]~start with 'r' (rcak)|rack",
    "algebra~11+x=16|5",
    "[ chitbuzz ]~start with 'm' (morla)|moral",
    "[ chitbuzz ]~start with 't' (iter)|tire",
    "[ chitbuzz ]~start with 'p' (pfoor)|proof",
    "[ chitbuzz ]~start with 's' (siut)|suit",
    "[ chitbuzz ]~start with 'u' (eunit)|unite",
    "math~7 - ? = 6|1",
    "[ chitbuzz ]~5 7 ? 9 11 7 21|3",
    "[ chitbuzz ]~start with 's' (esoh)|shoe",
    "[ chitbuzz ]~start with 'f' (atf)|fat",
    "[ chitbuzz ]~start with 'b' (abse)|base",
    "[ chitbuzz ]~start with 'm' (music)|music",
    "[ chitbuzz ]~start with 'i' (ice)|ice",
    "[ chitbuzz ]~start with 'p' (pta)|pat",
    "[ chitbuzz ]~start with 't' (ntee)|teen",
    "[ chitbuzz ]~start with 'l' (laek)|lake",
    "[ chitbuzz ]~start with 'k' (nokt)|knot",
    "[ chitbuzz ]~start with 'd' (dda)|dad",
    "[ chitbuzz ]~start with 'd' (dnkri)|drink",
    "[ chitbuzz ]~start with 'n' (enws)|news",
    "[ chitbuzz ]~start with 'c' (cklci)|click",
    "[ chitbuzz ]~start with 'o' (neo)|one",
    "math~? + 4 = 13|9",
    "[ chitbuzz ]~start with 'l' (clok)|lock",
    "[ chitbuzz ]~start with 'b' (tbe)|bet",
    "math~2 + 5 = ?|7",
    "[ chitbuzz ]~start with 'c' (cecyl)|cycle",
    "[ chitbuzz ]~start with 'j' (job)|job",
    "[ chitbuzz ]~start with 'u' (pu)|)|up)|",
    "[ chitbuzz ]~start with 's' (sxthi)|sixth",
    "[ chitbuzz ]~start with 'm' (ewmo)|meow",
    "[ chitbuzz ]~start with 'd' (dma)|dam",
    "[ chitbuzz ]~start with 'n' (neat)|neat",
    "[ chitbuzz ]~start with 'n' (tesn)|nest",
    "[ chitbuzz ]~start with 's' (sied)|side",
    "[ chitbuzz ]~2 3 2 4 ? 4 8|5",
    "[ chitbuzz ]~start with 'r' (rod)|rod",
    "[ chitbuzz ]~start with 'g' (eagt)|gate",
    "[ chitbuzz ]~start with 's' (aeucs)|sauce",
    "[ chitbuzz ]~start with 'b' (htob)|both",
    "[ chitbuzz ]~start with 'd' (dlyae)|delay",
    "[ chitbuzz ]~start with 't' (iths)|this",
    "[ chitbuzz ]~3 2 8 ? 9 36 38 37 148 150|10",
    "[ chitbuzz ]~2 0 0 ? 2 8 12 10 40 44|4",
    "[ chitbuzz ]~start with 'c' (acse)|case",
    "[ chitbuzz ]~start with 's' (edlis)|slide",
    "[ chitbuzz ]~start with 'a' (ami)|aim",
    "math~8 - 3 - ? = 3|2",
    "[ chitbuzz ]~start with 'w' (ewhel)|wheel",
    "[ chitbuzz ]~start with 's' (hiens)|shine",
    "[ chitbuzz ]~2 6 8 4 12 14 10 ? 32 28|30",
    "[ chitbuzz ]~start with 'l' (osle)|lose",
    "[ chitbuzz ]~start with 'f' (efel)|feel",
    "math~? x 5 = 10|2",
    "[ chitbuzz ]~start with 'f' (ulfl)|full",
    "[ chitbuzz ]~start with 'c' (rcy)|cry",
    "[ chitbuzz ]~start with 'f' (fnuny)|funny",
    "[ chitbuzz ]~4 1 ? 8 5 20 40|4",
    "[ chitbuzz ]~start with 't' (ttse)|test",
    "[ chitbuzz ]~start with 'p' (kpin)|pink",
    "[ chitbuzz ]~start with 'm' (rmoe)|more",
    "[ chitbuzz ]~2 5 6 24 27 28 112 ? 116 464|115",
    "math~6 x 9 = ?|54",
    "[ chitbuzz ]~start with 'h' (niht)|hint",
    "[ chitbuzz ]~start with 'r' (riot)|riot",
    "[ chitbuzz ]~start with 'c' (chair)|chair",
    "[ chitbuzz ]~start with 'i' (hcni)|inch",
    "[ chitbuzz ]~start with 'b' (tsbea)|beast",
    "[ chitbuzz ]~start with 'r' (iroat)|ratio",
    "[ chitbuzz ]~start with 'o' (nowre)|owner",
    "[ chitbuzz ]~start with 's' (ins)|sin",
    "math~7 - ? = 5|2",
    "[ chitbuzz ]~start with 's' (seom)|some",
    "[ chitbuzz ]~start with 'p' (aprty)|party",
    "[ chitbuzz ]~start with 's' (sdnta)|stand",
    "[ chitbuzz ]~start with 'f' (fta)|fat",
    "[ chitbuzz ]~start with 'e' (rveye)|every",
    "[ chitbuzz ]~start with 'r' (erul)|rule",
    "[ chitbuzz ]~6 9 7 28 31 29 116 119 ? 468|117",
    "[ chitbuzz ]~start with 'f' (flal)|fall",
    "[ chitbuzz ]~start with 'c' (cry)|cry",
    "math~2 - 2 = ?|0",
    "[ chitbuzz ]~start with 'p' (amlp)|palm",
    "[ chitbuzz ]~start with 'n' (kcne)|neck",
    "[ chitbuzz ]~start with 'f' (efir)|fire",
    "[ chitbuzz ]~start with 'c' (licmb)|climb",
    "[ chitbuzz ]~5 8 ? 20 23 20 80|5",
    "[ chitbuzz ]~start with 'f' (afct)|fact",
    "[ chitbuzz ]~7 6 12 14 ? 26 28|13",
    "[ chitbuzz ]~start with 'c' (crloo)|color",
    "math~6x5=?|30",
    "math~12+7=?|19",
    "[ chitbuzz ]~start with 'm' (imeov)|movie",
    "[ chitbuzz ]~start with 'p' (nopd)|pond",
    "[ chitbuzz ]~start with 'l' (ilke)|like",
    "[ chitbuzz ]~start with 'b' (bela)|bale",
    "[ chitbuzz ]~start with 'a' (lkiae)|alike",
    "[ chitbuzz ]~9 5 4 12 ? 7 21 17 16 48|8",
    "[ chitbuzz ]~start with 'c' (acrkc)|crack",
    "[ chitbuzz ]~start with 'a' (area)|area",
    "[ chitbuzz ]~4 8 11 8 ? 19 16|16",
    "[ chitbuzz ]~start with 's' (irths)|shirt",
    "[ chitbuzz ]~start with 'b' (eryub)|buyer",
    "[ chitbuzz ]~start with 's' (ksy)|sky",
    "[ chitbuzz ]~start with 'b' (oobk)|book",
    "[ chitbuzz ]~start with 's' (sloid)|solid",
    "[ chitbuzz ]~start with 's' (oras)|soar",
    "[ chitbuzz ]~start with 'l' (like)|like",
    "[ chitbuzz ]~start with 't' (ltle)|tell",
    "[ chitbuzz ]~start with 'r' (er)|re",
    "[ chitbuzz ]~start with 'c' (lcip)|clip",
    "[ chitbuzz ]~start with 'p' (psesr)|press",
    "[ chitbuzz ]~start with 'l' (elg)|leg",
    "[ chitbuzz ]~8 9 11 22 23 25 ?|50",
    "[ chitbuzz ]~? 8 9 6 10 11 8 12 13 10|4",
    "math~? - 2 = 0|2",
    "[ chitbuzz ]~start with 'p' (hpus)|push",
    "[ chitbuzz ]~start with 'l' (otl)|lot",
    "[ chitbuzz ]~9 27 25 21 63 61 57 ? 169 165|171",
    "[ chitbuzz ]~start with 't' (ltka)|talk",
    "[ chitbuzz ]~6 6 8 12 12 14 ? 18 20 24|18",
    "[ chitbuzz ]~start with 'l' (nlio)|lion",
    "[ chitbuzz ]~start with 'r' (lyarl)|rally",
    "[ chitbuzz ]~start with 'c' (aogrc)|cargo",
    "[ chitbuzz ]~3 0 ? 4 1 4 8|0",
    "[ chitbuzz ]~start with 'f' (amfe)|fame",
    "[ chitbuzz ]~start with 'w' (akew)|weak",
    "[ chitbuzz ]~start with 'c' (cap)|cap",
    "[ chitbuzz ]~start with 'h' (huge)|huge",
    "[ chitbuzz ]~5 3 6 10 ? 16 20 18 36 40|8",
    "[ chitbuzz ]~start with 's' (oesrc)|score",
    "math~? - 2 x 5 = 5|3",
    "[ chitbuzz ]~start with 'w' (haws)|wash",
    "[ chitbuzz ]~start with 'b' (bed)|bed",
    "math~? x 4 = 4|1",
    "math~5 x ? = 45|9",
    "[ chitbuzz ]~start with 'u' (nuerd)|under",
    "[ chitbuzz ]~start with 'a' (rma)|arm",
    "[ chitbuzz ]~start with 'c' (cdeo)|code",
    "[ chitbuzz ]~6 12 14 10 20 22 ?|18",
    "math~? / 8 = 1|8",
    "[ chitbuzz ]~start with 'f' (eifl)|file",
    "[ chitbuzz ]~start with 'l' (eadl)|lead",
    "[ chitbuzz ]~start with 'n' (tnu)|nut",
    "[ chitbuzz ]~start with 'r' (arle)|real",
    "[ chitbuzz ]~start with 'w' (allw)|wall",
    "math~2 - ? = 1|1",
    "[ chitbuzz ]~start with 'r' (hric)|rich",
    "[ chitbuzz ]~start with 'p' (nap)|pan",
    "[ chitbuzz ]~start with 'p' (taph)|path",
    "math~? - 2 x 5 = 5|3",
    "[ chitbuzz ]~1 4 3 ? 4 3 1|1",
    "[ chitbuzz ]~start with 'c' (lacm)|calm",
    "[ chitbuzz ]~start with 'p' (porve)|prove",
    "[ chitbuzz ]~start with 'h' (pyahp)|happy",
    "[ chitbuzz ]~start with 's' (esll)|sell",
    "[ chitbuzz ]~start with 'a' (wlola)|allow",
    "[ chitbuzz ]~start with 's' (osap)|soap",
    "[ chitbuzz ]~start with 'e' (dgee)|edge",
    "[ chitbuzz ]~start with 'g' (egt)|get",
    "[ chitbuzz ]~? 3 6 9 11 22 25 27 54 57|1",
    "[ chitbuzz ]~start with 'h' (ihhg)|high",
    "[ chitbuzz ]~start with 't' (hnit)|thin",
    "math~6 + 9 = ?|15",
    "[ chitbuzz ]~start with 'c' (csot)|cost",
    "[ chitbuzz ]~start with 's' (tsop)|stop",
    "[ chitbuzz ]~3 ? 13 12 48 49 48|12",
    "[ chitbuzz ]~? 4 8 10 6 10 12|8",
    "[ chitbuzz ]~start with 'h' (ih)|hi",
    "[ chitbuzz ]~9 7 28 28 ? 104 104|26",
    "[ chitbuzz ]~start with 'c' (ecckh)|check",
    "[ chitbuzz ]~start with 'h' (eohl)|hole",
    "[ chitbuzz ]~start with 'e' (enar)|earn",
    "[ chitbuzz ]~start with 'p' (ptan)|pant",
    "[ chitbuzz ]~start with 'c' (cadr)|card",
    "[ chitbuzz ]~start with 'j' (jug)|jug",
    "math~8 - ? - 1 = 5|2",
    "[ chitbuzz ]~start with 'f' (asft)|fast",
    "[ chitbuzz ]~start with 'd' (tedi)|diet",
    "[ chitbuzz ]~start with 'l' (eilf)|life",
    "[ chitbuzz ]~start with 'c' (orcp)|crop",
    "[ chitbuzz ]~start with 's' (hgsit)|sight",
    "[ chitbuzz ]~start with 'b' (bind)|bind",
    "[ chitbuzz ]~start with 'i' (tis)|its",
    "[ chitbuzz ]~start with 'j' (etj)|jet",
    "[ chitbuzz ]~start with 't' (thace)|teach",
    "[ chitbuzz ]~start with 'p' (pkci)|pick",
    "math~7 - ? - 5 = 0|2",
    "math~9 + ? - 3 = 9|3",
    "[ chitbuzz ]~start with 'f' (feer)|free",
    "[ chitbuzz ]~start with 'e' (ever)|ever",
    "[ chitbuzz ]~? 0 2 0 0 2 0 0 2 0|0",
    "[ chitbuzz ]~start with 'p' (pick)|pick",
    "[ chitbuzz ]~start with 'c' (ucgho)|cough",
    "[ chitbuzz ]~start with 'z' (zicn)|zinc",
    "[ chitbuzz ]~start with 'i' (lsima)|islam",
    "[ chitbuzz ]~start with 'n' (urnes)|nurse",
    "[ chitbuzz ]~start with 'u' (ualsu)|usual",
    "[ chitbuzz ]~start with 'p' (oupr)|pour",
    "math~5 x ? = 40|8",
    "[ chitbuzz ]~start with 'b' (ebd)|bed",
    "[ chitbuzz ]~start with 'g' (ugn)|gun",
    "[ chitbuzz ]~start with 'h' (ihs)|his",
    "math~1 + 1 + 4 = ?|6",
    "[ chitbuzz ]~start with 'b' (tabo)|boat",
    "[ chitbuzz ]~start with 'a' (atgne)|agent",
    "[ chitbuzz ]~start with 'a' (lasei)|aisle",
    "[ chitbuzz ]~start with 'f' (lfga)|flag",
    "[ chitbuzz ]~start with 'm' (xmi)|mix",
    "[ chitbuzz ]~start with 'p' (alptn)|plant",
    "[ chitbuzz ]~start with 'h' (sehr)|hers",
    "math~5 x ? = 45|9",
    "[ chitbuzz ]~start with 'd' (dekc)|deck",
    "[ chitbuzz ]~7 ? 5 20 22 18 72 74 70 280|9",
    "[ chitbuzz ]~6 24 24 23 92 92 ? 364 364 363|91",
    "[ chitbuzz ]~start with 'b' (drbi)|bird",
    "math~2 + ? = 3|1",
    "[ chitbuzz ]~8 6 18 18 16 48 48 46 138 ?|138",
    "[ chitbuzz ]~start with 'r' (tra)|rat",
    "math~9 + ? - 3 = 9|3",
    "[ chitbuzz ]~start with 'a' (obave)|above",
    "[ chitbuzz ]~start with 'd' (atad)|data",
    "[ chitbuzz ]~start with 'c' (tosc)|cost",
    "[ chitbuzz ]~start with 's' (das)|sad",
    "[ chitbuzz ]~start with 'm' (amny)|many",
    "math~? + 1 = 2|1",
    "[ chitbuzz ]~start with 'a' (aftre)|after",
    "[ chitbuzz ]~start with 'f' (fruit)|fruit",
    "[ chitbuzz ]~start with 'a' (aawke)|awake",
    "[ chitbuzz ]~? 10 12 9 18 20 17|5",
    "[ chitbuzz ]~start with 'w' (wielh)|while",
    "[ chitbuzz ]~start with 'w' (dowo)|wood",
    "[ chitbuzz ]~start with 'u' (sue)|use",
    "[ chitbuzz ]~start with 'c' (uct)|cut",
    "[ chitbuzz ]~start with 'p' (pwroe)|power",
    "[ chitbuzz ]~start with 'f' (eefr)|free",
    "[ chitbuzz ]~start with 'a' (aerna)|arena",
    "[ chitbuzz ]~start with 't' (eerht)|there",
    "[ chitbuzz ]~start with 'c' (oedc)|code",
    "[ chitbuzz ]~start with 'w' (erhew)|where",
    "[ chitbuzz ]~start with 'c' (ucerl)|cruel",
    "[ chitbuzz ]~start with 't' (tnue)|tune",
    "[ chitbuzz ]~start with 'w' (wiht)|with",
    "[ chitbuzz ]~start with 'b' (bare)|bare",
    "[ chitbuzz ]~start with 'k' (knig)|king",
    "[ chitbuzz ]~4 1 3 7 ? 6 10|4",
    "[ chitbuzz ]~start with 'c' (racd)|card",
    "[ chitbuzz ]~start with 'd' (ebdt)|debt",
    "[ chitbuzz ]~start with 's' (ipsll)|spill",
    "[ chitbuzz ]~? 21 19 15 45 43 39|7",
    "[ chitbuzz ]~3 5 2 ? 8 5 15|6",
    "[ chitbuzz ]~start with 's' (sum)|sum",
    "[ chitbuzz ]~start with 'd' (dree)|deer",
    "[ chitbuzz ]~9 8 16 14 13 ? 24|26",
    "[ chitbuzz ]~start with 's' (sick)|sick",
    "[ chitbuzz ]~start with 'p' (uslp)|plus",
    "[ chitbuzz ]~8 ? 2 4 0 -2 0 -4 -6 -4|4",
    "[ chitbuzz ]~start with 'l' (oald)|load",
    "[ chitbuzz ]~start with 'm' (erom)|more",
    "[ chitbuzz ]~start with 't' (oto)|too",
    "[ chitbuzz ]~start with 'l' (lblae)|label",
    "[ chitbuzz ]~start with 'o' (rtiob)|orbit",
    "[ chitbuzz ]~1 0 0 2 1 2 4 3 ? 8|6",
    "[ chitbuzz ]~5 8 5 ? 23 20 80 83 80 320|20",
    "[ chitbuzz ]~start with 'u' (ninuo)|union",
    "math~? x 4 = 20|5",
    "[ chitbuzz ]~9 10 13 9 10 13 9 10 ? 9|13",
    "[ chitbuzz ]~start with 'b' (kbloc)|block",
    "[ chitbuzz ]~start with 'm' (mass)|mass",
    "math~1 x ? = 4|4",
    "[ chitbuzz ]~start with 'c' (ehacs)|chase",
    "[ chitbuzz ]~start with 'l' (load)|load",
    "[ chitbuzz ]~start with 'l' (kcul)|luck",
    "[ chitbuzz ]~start with 't' (ckatr)|track",
    "[ chitbuzz ]~start with 'a' (isdae)|aside",
    "[ chitbuzz ]~start with 'g' (rigfe)|grief",
    "[ chitbuzz ]~start with 'b' (gba)|bag",
    "[ chitbuzz ]~start with 'f' (dolf)|fold",
    "[ chitbuzz ]~start with 'b' (ebat)|beat",
    "[ chitbuzz ]~start with 'p' (upmp)|pump",
    "math~7 - 2 - 1 = ?|4",
    "[ chitbuzz ]~start with 'h' (omhe)|home",
    "[ chitbuzz ]~start with 'l' (eoosl)|loose",
    "[ chitbuzz ]~start with 'd' (oldl)|doll",
    "[ chitbuzz ]~start with 'b' (bcka)|back",
    "[ chitbuzz ]~start with 's' (son)|son",
    "[ chitbuzz ]~9 36 ? 36 144 145 144 576 577 576|37",
    "[ chitbuzz ]~start with 'd' (ayd)|day",
    "[ chitbuzz ]~start with 'a' (graee)|agree",
    "[ chitbuzz ]~7 11 10 7 11 10 7 ? 10 7|11",
    "[ chitbuzz ]~start with 'f' (alfl)|fall",
    "[ chitbuzz ]~start with 'v' (avi)|via",
    "math~6 + 1 = ?|7",
    "[ chitbuzz ]~start with 's' (esflh)|shelf",
    "[ chitbuzz ]~start with 'a' (alepp)|apple",
    "[ chitbuzz ]~start with 't' (top)|top",
    "[ chitbuzz ]~start with 'w' (ewigh)|weigh",
    "[ chitbuzz ]~start with 'h' (hots)|host",
    "math~2x3=?|6",
    "[ chitbuzz ]~start with 'c' (ostca)|coast",
    "math~? - 1 = 5|6",
    "[ chitbuzz ]~start with 'l' (lot)|lot",
    "[ chitbuzz ]~start with 'w' (wnoag)|wagon",
    "[ chitbuzz ]~start with 'l' (elad)|lead",
    "[ chitbuzz ]~start with 'r' (toro)|root",
    "[ chitbuzz ]~start with 'p' (tpe)|pet",
    "[ chitbuzz ]~start with 't' (olto)|tool",
    "[ chitbuzz ]~start with 'v' (sruiv)|virus",
    "[ chitbuzz ]~8 5 20 24 ? 84 88|21",
    "[ chitbuzz ]~start with 'h' (toh)|hot",
    "math~2 - ? x 5 = 5|1",
    "[ chitbuzz ]~start with 's' (hops)|shop",
    "[ chitbuzz ]~start with 'b' (urbn)|burn",
    "[ chitbuzz ]~start with 'm' (emal)|meal",
    "[ chitbuzz ]~start with 'a' (oga)|ago",
    "[ chitbuzz ]~2 0 ? 5 3 5 8|2",
    "[ chitbuzz ]~start with 'p' (uprr)|purr",
    "[ chitbuzz ]~start with 'f' (tofo)|foot",
    "[ chitbuzz ]~start with 'o' (uro)|our",
    "[ chitbuzz ]~start with 'w' (oww)|wow",
    "[ chitbuzz ]~start with 'f' (fan)|fan",
    "[ chitbuzz ]~start with 't' (ater)|tear",
    "math~6 - ? = 5|1",
    "math~4 - ? = 1|3",
    "[ chitbuzz ]~start with 't' (htubm)|thumb",
    "[ chitbuzz ]~start with 's' (klis)|silk",
    "[ chitbuzz ]~start with 's' (stem)|stem",
    "[ chitbuzz ]~start with 'd' (dgo)|dog",
    "[ chitbuzz ]~8 12 48 ? 100 400 800|96",
    "[ chitbuzz ]~start with 'm' (uhcm)|much",
    "math~? - 2 = 5|7",
    "[ chitbuzz ]~start with 'w' (hwite)|white",
    "[ chitbuzz ]~start with 'e' (ego)|ego",
    "math~? - 1 x 5 = 5|2",
    "[ chitbuzz ]~start with 'p' (easpu)|pause",
    "[ chitbuzz ]~start with 'h' (llhe)|hell",
    "[ chitbuzz ]~start with 'f' (lfy)|fly",
    "[ chitbuzz ]~start with 'i' (adile)|ideal",
    "[ chitbuzz ]~8 16 20 21 42 46 ?|47",
    "[ chitbuzz ]~start with 'p' (niprt)|print",
    "[ chitbuzz ]~start with 'c' (ocrd)|cord",
    "[ chitbuzz ]~start with 'w' (wet)|wet",
    "[ chitbuzz ]~start with 'g' (dlog)|gold",
    "[ chitbuzz ]~start with 'p' (eohpn)|phone",
    "[ chitbuzz ]~start with 's' (lliks)|skill",
    "[ chitbuzz ]~start with 'w' (weid)|wide",
    "math~5 x ? = 25|5",
    "[ chitbuzz ]~start with 'o' (vroe)|over",
    "[ chitbuzz ]~start with 's' (nsoo)|soon",
    "[ chitbuzz ]~start with 'b' (bring)|bring",
    "[ chitbuzz ]~7 7 8 6 ? 7 5 5 6 4|6",
    "[ chitbuzz ]~6 12 11 8 16 ? 12|15",
    "[ chitbuzz ]~start with 's' (smiel)|smile",
    "[ chitbuzz ]~start with 'o' (rdore)|order",
    "math~? x 4 = 16|4",
    "[ chitbuzz ]~start with 't' (ettas)|taste",
    "[ chitbuzz ]~start with 'p' (put)|put",
    "[ chitbuzz ]~start with 'b' (boy)|boy",
    "[ chitbuzz ]~start with 'e' (aceh)|each",
    "[ chitbuzz ]~start with 'j' (tujs)|just",
    "[ chitbuzz ]~start with 'd' (udst)|dust",
    "[ chitbuzz ]~start with 'l' (lamp)|lamp",
    "[ chitbuzz ]~start with 'w' (etw)|wet",
    "math~18กา3=?|6",
    "[ chitbuzz ]~1 ? 8 12 15 30 34|4",
    "math~32กา8=?|4",
    "[ chitbuzz ]~start with 'a' (am)|am",
    "[ chitbuzz ]~start with 'd' (idrev)|drive",
    "[ chitbuzz ]~start with 'a' (pyalp)|apply",
    "[ chitbuzz ]~start with 'p' (yap)|pay",
    "math~3 - ? = 1|2",
    "[ chitbuzz ]~start with 'l' (oolk)|look",
    "[ chitbuzz ]~start with 'p' (tspa)|past",
    "[ chitbuzz ]~start with 'r' (ardo)|road",
    "[ chitbuzz ]~start with 'h' (andh)|hand",
    "[ chitbuzz ]~start with 'r' (errvi)|river",
    "[ chitbuzz ]~9 10 13 9 10 13 ?|9",
    "[ chitbuzz ]~start with 's' (isol)|soil",
    "[ chitbuzz ]~start with 'p' (pnioa)|piano",
    "math~9 - 3 = ?|6",
    "[ chitbuzz ]~start with 'a' (amdit)|admit",
    "[ chitbuzz ]~start with 'd' (dgru)|drug",
    "[ chitbuzz ]~start with 'b' (leybl)|belly",
    "math~? x 5 = 30|6",
    "[ chitbuzz ]~start with 'a' (aarml)|alarm",
    "[ chitbuzz ]~start with 'o' (poen)|open",
    "[ chitbuzz ]~start with 't' (rtuyl)|truly",
    "[ chitbuzz ]~start with 'b' (xob)|box",
    "[ chitbuzz ]~start with 'f' (mflea)|flame",
    "[ chitbuzz ]~start with 'm' (smes)|mess",
    "[ chitbuzz ]~start with 'w' (wvea)|wave",
    "math~? / 6 x 9 = 3|2",
    "[ chitbuzz ]~9 11 9 36 38 36 ? 146 144 576|144",
    "math~4 + ? = 12|8",
    "[ chitbuzz ]~start with 'c' (ifehc)|chief",
    "[ chitbuzz ]~start with 's' (puser)|super",
    "[ chitbuzz ]~start with 'c' (ocol)|cool",
    "[ chitbuzz ]~start with 's' (isr)|sir",
    "[ chitbuzz ]~start with 'n' (monr)|norm",
    "[ chitbuzz ]~start with 's' (nos)|son",
    "[ chitbuzz ]~start with 'n' (otne)|note",
    "[ chitbuzz ]~start with 'l' (azly)|lazy",
    "[ chitbuzz ]~5 3 4 7 5 6 9 7 ? 11|8",
    "[ chitbuzz ]~start with 'f' (leef)|flee",
    "[ chitbuzz ]~start with 'm' (ilmk)|milk",
    "[ chitbuzz ]~start with 'n' (wno)|now",
    "[ chitbuzz ]~start with 'b' (nblka)|blank",
    "[ chitbuzz ]~start with 'm' (msr)|mrs",
    "[ chitbuzz ]~start with 'i' (ilmpy)|imply",
    "[ chitbuzz ]~start with 'w' (wdil)|wild",
    "[ chitbuzz ]~start with 'b' (obil)|boil",
    "[ chitbuzz ]~start with 'l' (lreiv)|liver",
    "[ chitbuzz ]~start with 'c' (inoc)|coin",
    "[ chitbuzz ]~start with 'p' (eshap)|phase",
    "[ chitbuzz ]~start with 'c' (cefh)|chef",
    "[ chitbuzz ]~start with 's' (isnk)|sink",
    "[ chitbuzz ]~start with 'f' (tlfa)|flat",
    "[ chitbuzz ]~start with 'c' (hcalk)|chalk",
    "[ chitbuzz ]~start with 'j' (ejwle)|jewel",
    "[ chitbuzz ]~4 8 12 9 18 ? 19 38 42 39|22",
    "[ chitbuzz ]~start with 'e' (oche)|echo",
    "[ chitbuzz ]~2 2 4 ? 2 4 2|2",
    "[ chitbuzz ]~start with 'm' (smas)|mass",
    "[ chitbuzz ]~start with 's' (hse)|she",
    "[ chitbuzz ]~start with 'e' (ect)|etc",
    "[ chitbuzz ]~start with 'a' (sa)|as",
    "[ chitbuzz ]~start with 's' (hse)|she",
    "[ chitbuzz ]~start with 't' (try)|try",
    "[ chitbuzz ]~6 ? 15 17 16 48 50|5",
    "[ chitbuzz ]~start with 't' (ebut)|tube",
    "[ chitbuzz ]~7 6 6 9 8 8 ?|11",
    "[ chitbuzz ]~start with 's' (nasd)|sand",
    "[ chitbuzz ]~start with 'w' (wega)|wage",
    "math~7 - ? - 1 = 4|2",
    "[ chitbuzz ]~start with 'd' (ldaiy)|daily",
    "math~? - 2 + 1 = 6|7",
    "[ chitbuzz ]~start with 'p' (llpu)|pull",
    "[ chitbuzz ]~start with 'r' (lorl)|roll",
    "[ chitbuzz ]~start with 'm' (mrak)|mark",
    "[ chitbuzz ]~start with 'k' (inkfe)|knife",
    "[ chitbuzz ]~start with 'a' (auot)|auto",
    "[ chitbuzz ]~start with 'c' (iclff)|cliff",
    "math~8 / ? = 4|2",
    "[ chitbuzz ]~start with 'h' (hair)|hair",
    "[ chitbuzz ]~start with 'f' (afte)|fate",
    "[ chitbuzz ]~start with 'k' (ekep)|keep",
    "[ chitbuzz ]~start with 'p' (prat)|part",
    "[ chitbuzz ]~start with 'r' (irb)|rib",
    "math~9x8=?|72",
    "[ chitbuzz ]~start with 'l' (elt)|let",
    "[ chitbuzz ]~start with 'c' (hcop)|chop",
    "[ chitbuzz ]~start with 'v' (vats)|vast",
    "[ chitbuzz ]~start with 't' (alott)|total",
    "[ chitbuzz ]~start with 'e' (neev)|even",
    "[ chitbuzz ]~start with 'l' (ild)|lid",
    "[ chitbuzz ]~start with 'm' (emat)|meat",
    "[ chitbuzz ]~start with 'r' (iran)|rain",
    "[ chitbuzz ]~start with 'd' (odg)|dog",
    "[ chitbuzz ]~start with 't' (edit)|tide",
    "[ chitbuzz ]~start with 'p' (pig)|pig",
    "[ chitbuzz ]~start with 'f' (fmor)|from",
    "[ chitbuzz ]~start with 's' (rstip)|strip",
    "[ chitbuzz ]~start with 'h' (dlho)|hold",
    "[ chitbuzz ]~start with 'j' (pujm)|jump",
    "[ chitbuzz ]~start with 'f' (rmof)|form",
    "[ chitbuzz ]~5 8 9 6 ? 10 7|9",
    "[ chitbuzz ]~6 6 9 7 7 10 ? 8 11 9|8",
    "[ chitbuzz ]~start with 'd' (derss)|dress",
    "[ chitbuzz ]~start with 'h' (ohw)|how",
    "[ chitbuzz ]~start with 'c' (cvoer)|cover",
    "[ chitbuzz ]~start with 't' (ate)|tea",
    "[ chitbuzz ]~start with 'w' (stwe)|west",
    "[ chitbuzz ]~start with 's' (skin)|skin",
    "[ chitbuzz ]~0 ? 2 -1 -2 0 -3|0",
    "[ chitbuzz ]~start with 's' (tffsa)|staff",
    "[ chitbuzz ]~start with 'l' (ovelr)|lover",
    "[ chitbuzz ]~start with 'p' (izpaz)|pizza",
    "math~3 - ? = 0|3",
    "[ chitbuzz ]~start with 'e' (ear)|ear",
    "[ chitbuzz ]~start with 'p' (piatn)|paint",
    "[ chitbuzz ]~start with 'e' (tae)|eat",
    "[ chitbuzz ]~start with 'w' (grwno)|wrong",
    "[ chitbuzz ]~start with 'a' (ayn)|any",
    "[ chitbuzz ]~start with 'e' (lees)|else",
    "[ chitbuzz ]~start with 'r' (ray)|ray",
    "math~2+5=?|7",
    "math~6 / 6 = ?|1",
    "[ chitbuzz ]~start with 'h' (hreb)|herb",
    "[ chitbuzz ]~start with 'i' (its)|its",
    "[ chitbuzz ]~start with 's' (oslt)|slot",
    "[ chitbuzz ]~start with 't' (cixot)|toxic",
    "[ chitbuzz ]~start with 'g' (glir)|girl",
    "[ chitbuzz ]~start with 'j' (iejuc)|juice",
    "math~? - 2 = 0|2",
    "math~8 / 2 = ?|4",
    "[ chitbuzz ]~start with 'h' (nahg)|hang",
    "[ chitbuzz ]~start with 'n' (evenr)|never",
    "[ chitbuzz ]~start with 'l' (lyda)|lady",
    "[ chitbuzz ]~start with 'c' (coil)|coil",
    "[ chitbuzz ]~start with 'l' (ploo)|loop",
    "[ chitbuzz ]~start with 'a' (ratpa)|apart",
    "[ chitbuzz ]~0 -2 -1 ? 0 1 4 2 3 6|2",
    "[ chitbuzz ]~start with 's' (speda)|spade",
    "[ chitbuzz ]~start with 'm' (mxide)|mixed",
    "[ chitbuzz ]~start with 'b' (iubld)|build",
    "[ chitbuzz ]~start with 'g' (get)|get",
    "[ chitbuzz ]~start with 't' (too)|too",
    "[ chitbuzz ]~start with 'h' (okho)|hook",
    "[ chitbuzz ]~start with 'w' (keew)|week",
    "[ chitbuzz ]~start with 't' (atil)|tail",
    "[ chitbuzz ]~start with 'l' (laem)|lame",
    "[ chitbuzz ]~start with 'b' (btut)|butt",
    "[ chitbuzz ]~start with 'b' (bone)|bone",
    "[ chitbuzz ]~start with 'k' (gink)|king",
    "[ chitbuzz ]~start with 'd' (idve)|dive",
    "[ chitbuzz ]~start with 'p' (apge)|page",
    "[ chitbuzz ]~start with 'n' (wne)|new",
    "[ chitbuzz ]~start with 'c' (crsso)|cross",
    "[ chitbuzz ]~6 8 12 10 12 16 14 16 ? 18|20",
    "[ chitbuzz ]~start with 'c' (chin)|chin",
    "[ chitbuzz ]~start with 's' (sedn)|send",
    "[ chitbuzz ]~start with 'f' (ofdo)|food",
    "[ chitbuzz ]~start with 'f' (lfow)|flow",
    "[ chitbuzz ]~start with 'g' (glove)|glove",
    "[ chitbuzz ]~start with 'f' (vfie)|five",
    "[ chitbuzz ]~start with 't' (tmie)|time",
    "[ chitbuzz ]~start with 't' (anth)|than",
    "[ chitbuzz ]~5 1 4 5 1 4 5 1 4 ?|5",
    "[ chitbuzz ]~start with 's' (fihts)|shift",
    "[ chitbuzz ]~start with 'g' (gas)|gas",
    "[ chitbuzz ]~4 1 4 8 5 8 ?|12",
    "[ chitbuzz ]~start with 'w' (iwfe)|wife",
    "[ chitbuzz ]~start with 'd' (kdie)|dike",
    "math~1 + 5 = ?|6",
    "[ chitbuzz ]~6 7 9 18 19 21 42 43 ? 90|45",
    "algebra~2+x=3|1",
    "[ chitbuzz ]~start with 'l' (less)|less",
    "[ chitbuzz ]~start with 's' (stae)|seat",
    "[ chitbuzz ]~start with 'a' (awati)|await",
    "[ chitbuzz ]~start with 'c' (nich)|chin",
    "[ chitbuzz ]~0 2 0 0 ? 0 0|2",
    "[ chitbuzz ]~start with 'v' (vialt)|vital",
    "[ chitbuzz ]~start with 'o' (onion)|onion",
    "[ chitbuzz ]~start with 'f' (ofld)|fold",
    "[ chitbuzz ]~? 1 3 7 7 9 13 13 15 19|1",
    "[ chitbuzz ]~start with 'p' (nlap)|plan",
    "[ chitbuzz ]~9 7 14 ? 16 32 36 34 68 72|18",
    "[ chitbuzz ]~start with 'e' (tilee)|elite",
    "[ chitbuzz ]~start with 'p' (oopr)|poor",
    "[ chitbuzz ]~start with 's' (etsp)|step",
    "[ chitbuzz ]~start with 'p' (pelo)|pole",
    "[ chitbuzz ]~7 9 13 39 41 45 135 137 ? 423|141",
    "[ chitbuzz ]~start with 'l' (nela)|lean",
    "[ chitbuzz ]~start with 'a' (fawlu)|awful",
    "[ chitbuzz ]~start with 'w' (awek)|wake",
    "[ chitbuzz ]~6 8 12 ? 12 16 14|10",
    "[ chitbuzz ]~start with 's' (lsam)|slam",
    "[ chitbuzz ]~start with 'c' (ckocl)|clock",
    "[ chitbuzz ]~start with 'f' (few)|few",
    "[ chitbuzz ]~6 4 6 9 7 9 12 10 12 ?|15",
    "[ chitbuzz ]~2 2 6 4 4 8 ? 6 10 8|6",
    "[ chitbuzz ]~start with 'g' (teag)|gate",
    "[ chitbuzz ]~start with 'd' (drea)|dear",
    "[ chitbuzz ]~start with 's' (ptees)|steep",
    "[ chitbuzz ]~start with 't' (wreot)|tower",
    "math~5 + 8 = ?|13",
    "[ chitbuzz ]~start with 'h' (hafl)|half",
    "[ chitbuzz ]~start with 'v' (vdail)|valid",
    "[ chitbuzz ]~start with 'p' (alpne)|panel",
    "[ chitbuzz ]~4 1 ? 8 5 20 40 37 148 296|4",
    "[ chitbuzz ]~start with 'a' (retal)|alter",
    "[ chitbuzz ]~9 36 32 31 ? 120 119|124",
    "math~12-3=?|9",
    "[ chitbuzz ]~start with 't' (iet)|tie",
    "[ chitbuzz ]~? 7 8 5 5 6 3|7",
    "[ chitbuzz ]~start with 'c' (ucp)|cup",
    "[ chitbuzz ]~4 16 19 18 72 75 74 ? 299 298|296",
    "[ chitbuzz ]~start with 'i' (iead)|idea",
    "[ chitbuzz ]~0 0 0 2 6 ? 26 78 312 314|24",
    "[ chitbuzz ]~start with 'i' (lil)|ill",
    "[ chitbuzz ]~start with 's' (hsut)|shut",
    "[ chitbuzz ]~start with 'b' (ibnld)|blind",
    "[ chitbuzz ]~8 9 ? 16 17 16 32|8",
    "[ chitbuzz ]~start with 'b' (osbs)|boss",
    "[ chitbuzz ]~start with 's' (suer)|sure",
    "[ chitbuzz ]~start with 'e' (ivel)|evil",
    "[ chitbuzz ]~8 8 9 7 7 ? 6|8",
    "[ chitbuzz ]~start with 'l' (evlle)|level",
    "math~1 + 9 = ?|10",
    "[ chitbuzz ]~start with 'r' (eral)|real",
    "[ chitbuzz ]~start with 's' (ecsli)|slice",
    "[ chitbuzz ]~start with 'e' (ynve)|envy",
    "math~6 x ? = 6|1",
    "[ chitbuzz ]~start with 'b' (abrve)|brave",
    "[ chitbuzz ]~start with 'g' (vegi)|give",
    "math~6 + ? = 15|9",
    "[ chitbuzz ]~start with 'b' (sabic)|basic",
    "math~4-2=?|2",
    "[ chitbuzz ]~start with 't' (rtoop)|troop",
    "[ chitbuzz ]~start with 'w' (iwll)|will",
    "[ chitbuzz ]~start with 'd' (llrid)|drill",
    "[ chitbuzz ]~start with 't' (chitk)|thick",
    "[ chitbuzz ]~start with 's' (sun)|sun",
    "[ chitbuzz ]~3 0 0 4 1 3 ?|7",
    "[ chitbuzz ]~start with 'n' (tnex)|next",
    "[ chitbuzz ]~start with 'o' (off)|off",
    "[ chitbuzz ]~start with 'e' (txei)|exit",
    "[ chitbuzz ]~start with 'm' (stim)|mist",
    "[ chitbuzz ]~0 ? 3 -1 -1 2 -2 -2 1 -3|0",
    "[ chitbuzz ]~start with 'g' (gsa)|gas",
    "[ chitbuzz ]~start with 'r' (rude)|rude",
    "[ chitbuzz ]~start with 'q' (qietu)|quiet",
    "[ chitbuzz ]~start with 't' (rtmi)|trim",
    "math~8 - 2 - ? = 0|6",
    "[ chitbuzz ]~start with 'w' (wlel)|well",
    "[ chitbuzz ]~start with 'a' (oenal)|alone",
    "[ chitbuzz ]~start with 'g' (gprae)|grape",
    "math~4 - 3 = ?|1",
    "[ chitbuzz ]~start with 'r' (hrguo)|rough",
    "[ chitbuzz ]~3 6 18 72 75 225 900 ? 2709 10836|903",
    "[ chitbuzz ]~start with 'a' (rtcao)|actor",
    "[ chitbuzz ]~start with 'h' (haetr)|heart",
    "[ chitbuzz ]~start with 'm' (em)|me",
    "[ chitbuzz ]~start with 'w' (aws)|was",
    "[ chitbuzz ]~start with 's' (tis)|sit",
    "[ chitbuzz ]~start with 'b' (ibg)|big",
    "[ chitbuzz ]~start with 't' (tlie)|tile",
    "[ chitbuzz ]~8 4 ? 5 1 1 2|4",
    "math~8 - 2 - ? = 0|6",
    "math~8 / 2 - 2 = ?|2",
    "[ chitbuzz ]~start with 'p' (ipcer)|price",
    "[ chitbuzz ]~5 7 5 ? 17 15 45|15",
    "[ chitbuzz ]~start with 'j' (ojek)|joke",
    "[ chitbuzz ]~start with 'b' (darnb)|brand",
    "[ chitbuzz ]~start with 'd' (dull)|dull",
    "[ chitbuzz ]~start with 'c' (tyic)|city",
    "[ chitbuzz ]~start with 'i' (eiuss)|issue",
    "[ chitbuzz ]~8 5 10 ? 11 22 26 23 46 50|14",
    "[ chitbuzz ]~start with 'r' (bur)|rub",
    "[ chitbuzz ]~start with 't' (atrde)|trade",
    "[ chitbuzz ]~start with 'u' (hu)|uh",
    "math~? / 7 = 1|7",
    "[ chitbuzz ]~start with 't' (toe)|toe",
    "[ chitbuzz ]~start with 'd' (hcdut)|dutch",
    "[ chitbuzz ]~start with 's' (lows)|slow",
    "[ chitbuzz ]~start with 'w' (hwo)|who",
    "[ chitbuzz ]~start with 'm' (simtd)|midst",
    "[ chitbuzz ]~start with 'd' (ksed)|desk",
    "[ chitbuzz ]~start with 'b' (tenb)|bent",
    "[ chitbuzz ]~start with 's' (oisl)|soil",
    "[ chitbuzz ]~start with 'o' (eonc)|once",
    "[ chitbuzz ]~3 ? 6 2 6 3 -1|9",
    "[ chitbuzz ]~start with 'p' (cepei)|piece",
    "[ chitbuzz ]~start with 's' (estle)|steel",
    "[ chitbuzz ]~start with 't' (rsttu)|trust",
    "[ chitbuzz ]~start with 'a' (da)|ad",
    "math~9 + ? = 12|3",
    "[ chitbuzz ]~start with 'c' (chets)|chest",
    "[ chitbuzz ]~start with 'f' (fool)|fool",
    "[ chitbuzz ]~start with 'o' (aoky)|okay",
    "math~9 + ? = 17|8",
    "[ chitbuzz ]~start with 'a' (ablmu)|album",
    "[ chitbuzz ]~start with 'g' (eagm)|game",
    "[ chitbuzz ]~start with 'b' (dabn)|band",
    "math~5 + ? = 13|8",
    "math~5 + ? = 13|8",
    "[ chitbuzz ]~start with 'l' (meil)|lime",
    "[ chitbuzz ]~start with 'l' (kolo)|look",
    "[ chitbuzz ]~start with 'm' (yomar)|mayor",
    "[ chitbuzz ]~start with 'p' (tnpio)|point",
    "[ chitbuzz ]~start with 't' (unet)|tune",
    "[ chitbuzz ]~start with 'h' (eehl)|heel",
    "[ chitbuzz ]~start with 'w' (awlk)|walk",
    "[ chitbuzz ]~start with 'r' (tesr)|rest",
    "[ chitbuzz ]~start with 'c' (bomc)|comb",
    "[ chitbuzz ]~start with 'b' (libnk)|blink",
    "[ chitbuzz ]~1 2 5 4 8 11 10 ? 23 22|20",
    "[ chitbuzz ]~? -1 0 3 2 3 6|0",
    "[ chitbuzz ]~start with 'c' (whec)|chew",
    "[ chitbuzz ]~start with 'b' (bubl)|bulb",
    "math~4 + ? / 2 = 6|8",
    "[ chitbuzz ]~start with 'r' (uroet)|route",
    "[ chitbuzz ]~start with 'p' (ealp)|pale",
    "[ chitbuzz ]~1 3 3 2 6 6 ?|5",
    "[ chitbuzz ]~start with 'f' (rfo)|for",
    "math~? - 2 = 5|7",
    "[ chitbuzz ]~start with 'c' (atc)|cat",
    "math~4 x 3 = ?|12",
    "[ chitbuzz ]~start with 'w' (wise)|wise",
    "[ chitbuzz ]~start with 'y' (yes)|yes",
    "[ chitbuzz ]~start with 's' (msoe)|some",
    "[ chitbuzz ]~start with 'd' (depth)|depth",
    "[ chitbuzz ]~start with 'a' (gea)|age",
    "[ chitbuzz ]~start with 'n' (ond)|nod",
    "[ chitbuzz ]~start with 'c' (echek)|cheek",
    "[ chitbuzz ]~start with 's' (dsne)|send",
    "[ chitbuzz ]~start with 'd' (dbmu)|dumb",
    "[ chitbuzz ]~start with 'b' (bnor)|born",
    "[ chitbuzz ]~start with 'l' (snle)|lens",
    "math~? + 8 = 13|5",
    "[ chitbuzz ]~start with 'm' (nime)|mine",
    "[ chitbuzz ]~6 7 5 ? 8 6 8|7",
    "[ chitbuzz ]~start with 'e' (aset)|east",
    "[ chitbuzz ]~start with 'r' (ort)|rot",
    "[ chitbuzz ]~start with 'c' (acn)|can",
    "[ chitbuzz ]~start with 'b' (abr)|bar",
    "[ chitbuzz ]~start with 's' (ysa)|say",
    "[ chitbuzz ]~start with 'n' (nsoe)|nose",
    "[ chitbuzz ]~start with 's' (iswm)|swim",
    "[ chitbuzz ]~start with 'f' (ihfft)|fifth",
    "math~4 x 3 = ?|12",
    "[ chitbuzz ]~start with 's' (esx)|sex",
    "[ chitbuzz ]~start with 'b' (bow)|bow",
    "[ chitbuzz ]~start with 'w' (ndouw)|wound",
    "[ chitbuzz ]~start with 'a' (gaain)|again",
    "[ chitbuzz ]~start with 'e' (atrxe)|extra",
    "math~81กา9=?|9",
    "[ chitbuzz ]~start with 'f' (ixf)|fix",
    "[ chitbuzz ]~start with 'l' (kcla)|lack",
    "[ chitbuzz ]~start with 's' (iszee)|seize",
    "math~7 / 1 + 1 = ?|8",
    "[ chitbuzz ]~start with 'b' (uble)|blue",
    "[ chitbuzz ]~start with 'z' (ezro)|zero",
    "[ chitbuzz ]~start with 'r' (orund)|round",
    "[ chitbuzz ]~start with 'm' (emet)|meet",
    "[ chitbuzz ]~start with 'e' (yeas)|easy",
    "[ chitbuzz ]~start with 'm' (tmuno)|mount",
    "[ chitbuzz ]~start with 'g' (hogst)|ghost",
    "[ chitbuzz ]~start with 'c' (achin)|chain",
    "[ chitbuzz ]~0 3 2 2 5 4 4 7 ? 6|6",
    "[ chitbuzz ]~start with 'j' (ionj)|join",
    "[ chitbuzz ]~start with 'w' (how)|who",
    "[ chitbuzz ]~start with 'a' (dan)|and",
    "[ chitbuzz ]~start with 'p' (pmup)|pump",
    "[ chitbuzz ]~start with 'g' (garev)|grave",
    "[ chitbuzz ]~start with 't' (latl)|tall",
    "[ chitbuzz ]~start with 's' (tisr)|stir",
    "[ chitbuzz ]~start with 'l' (nglo)|long",
    "[ chitbuzz ]~start with 'o' (treoh)|other",
    "[ chitbuzz ]~start with 't' (teyp)|type",
    "[ chitbuzz ]~start with 'm' (mina)|main",
    "[ chitbuzz ]~start with 's' (kaesn)|snake",
    "[ chitbuzz ]~start with 'h' (uamhn)|human",
    "[ chitbuzz ]~start with 'g' (ugied)|guide",
    "[ chitbuzz ]~start with 'c' (comb)|comb",
    "[ chitbuzz ]~start with 'b' (yb)|by",
    "[ chitbuzz ]~start with 'f' (nfila)|final",
    "[ chitbuzz ]~start with 'm' (emdla)|medal",
    "[ chitbuzz ]~start with 's' (set)|set",
    "[ chitbuzz ]~? 8 8 24 26 26 78 80 80 240|6",
    "[ chitbuzz ]~start with 'c' (olcse)|close",
    "math~? x 5 = 25|5",
    "[ chitbuzz ]~start with 'b' (anb)|ban",
    "[ chitbuzz ]~start with 'o' (ko)|ok",
    "[ chitbuzz ]~start with 'b' (lbul)|bull",
    "[ chitbuzz ]~start with 'k' (kidn)|kind",
    "[ chitbuzz ]~start with 'l' (mpul)|lump",
    "[ chitbuzz ]~start with 's' (sales)|sales",
    "[ chitbuzz ]~6 24 21 ? 80 77 76|20",
    "[ chitbuzz ]~? 0 0 2 1 3 5|1",
    "[ chitbuzz ]~start with 'l' (aertl)|later",
    "[ chitbuzz ]~start with 'f' (rfomu)|forum",
    "[ chitbuzz ]~start with 'h' (tahe)|heat",
    "[ chitbuzz ]~start with 'r' (aertc)|react",
    "[ chitbuzz ]~start with 'f' (farm)|farm",
    "math~5 x ? = 40|8",
    "[ chitbuzz ]~6 ? 3 6 3 3 6|3",
    "math~9 / 3 = ?|3",
    "[ chitbuzz ]~start with 'w' (owrk)|work",
    "[ chitbuzz ]~start with 'c' (lcal)|call",
    "algebra~15-x=7|8",
    "[ chitbuzz ]~start with 't' (tax)|tax",
    "[ chitbuzz ]~start with 'w' (giwn)|wing",
    "[ chitbuzz ]~start with 't' (thin)|thin",
    "math~6 + ? = 7|1",
    "[ chitbuzz ]~start with 'f' (for)|for",
    "[ chitbuzz ]~3 1 -2 ? -1 -4 -1|1",
    "[ chitbuzz ]~start with 's' (mosrt)|storm",
    "[ chitbuzz ]~start with 's' (trkis)|skirt",
    "[ chitbuzz ]~start with 'm' (ojamr)|major",
    "[ chitbuzz ]~start with 'c' (sace)|case",
    "[ chitbuzz ]~start with 'b' (lbeu)|blue",
    "[ chitbuzz ]~start with 'w' (wax)|wax",
    "[ chitbuzz ]~2 0 0 3 1 ? 5|2",
    "[ chitbuzz ]~start with 's' (rspya)|spray",
    "math~63กา9=?|7",
    "[ chitbuzz ]~start with 'n' (noet)|note",
    "[ chitbuzz ]~start with 'r' (urn)|run",
    "[ chitbuzz ]~start with 'w' (warm)|warm",
    "[ chitbuzz ]~start with 'f' (frehs)|fresh",
    "[ chitbuzz ]~start with 'd' (adn)|dna",
    "math~7 - 2 = ?|5",
    "math~4 x ? = 32|8",
    "[ chitbuzz ]~start with 'r' (lypre)|reply",
    "[ chitbuzz ]~start with 's' (cskoh)|shock",
    "[ chitbuzz ]~start with 'p' (peag)|page",
    "[ chitbuzz ]~start with 'b' (adb)|bad",
    "[ chitbuzz ]~start with 'l' (yla)|lay",
    "[ chitbuzz ]~start with 'f' (hifs)|fish",
    "[ chitbuzz ]~start with 'h' (hook)|hook",
    "[ chitbuzz ]~start with 'b' (sabe)|base",
    "math~7-4=?|3",
    "[ chitbuzz ]~start with 'w' (orwdl)|world",
    "[ chitbuzz ]~start with 'b' (gabn)|bang",
    "math~9 x 4 = ?|36",
    "[ chitbuzz ]~2 ? 8 7 28 28 27|8",
    "[ chitbuzz ]~start with 'w' (lwel)|well",
    "[ chitbuzz ]~start with 'q' (quene)|queen",
    "[ chitbuzz ]~2 1 2 4 ? 6 8|3",
    "[ chitbuzz ]~start with 'b' (aembl)|blame",
    "[ chitbuzz ]~start with 'a' (aid)|aid",
    "[ chitbuzz ]~start with 'w' (iswh)|wish",
    "[ chitbuzz ]~start with 's' (psend)|spend",
    "[ chitbuzz ]~start with 'd' (bted)|debt",
    "[ chitbuzz ]~start with 's' (osrt)|sort",
    "[ chitbuzz ]~start with 'm' (emor)|more",
    "[ chitbuzz ]~start with 'l' (lses)|less",
    "[ chitbuzz ]~start with 'w' (hnwe)|when",
    "[ chitbuzz ]~start with 'h' (nohye)|honey",
    "math~3 - 3 / 6 = ?|0",
    "[ chitbuzz ]~start with 'm' (maet)|meat",
    "[ chitbuzz ]~start with 'n' (eicn)|nice",
    "[ chitbuzz ]~3 7 9 18 22 24 ?|48",
    "[ chitbuzz ]~start with 'e' (jneyo)|enjoy",
    "[ chitbuzz ]~9 ? 12 12 16 15 15|13",
    "[ chitbuzz ]~start with 's' (xse)|sex",
    "[ chitbuzz ]~start with 'l' (ilenn)|linen",
    "[ chitbuzz ]~start with 'd' (oprd)|drop",
    "[ chitbuzz ]~start with 'b' (rdib)|bird",
    "[ chitbuzz ]~6 12 15 14 28 ? 30 60 63 62|31",
    "[ chitbuzz ]~start with 'm' (yhtm)|myth",
    "[ chitbuzz ]~start with 't' (twin)|twin",
    "[ chitbuzz ]~start with 'h' (evah)|have",
    "[ chitbuzz ]~start with 'm' (isms)|miss",
    "[ chitbuzz ]~2 ? 0 1 -1 -3 -2|0",
    "[ chitbuzz ]~start with 'e' (typme)|empty",
    "[ chitbuzz ]~start with 's' (asy)|say",
    "[ chitbuzz ]~start with 'p' (apd)|pad",
    "math~5 + ? = 14|9",
    "[ chitbuzz ]~start with 's' (strat)|start",
    "[ chitbuzz ]~start with 's' (lisp)|slip",
    "[ chitbuzz ]~start with 't' (tnha)|than",
    "[ chitbuzz ]~start with 't' (tten)|tent",
    "[ chitbuzz ]~start with 'y' (sey)|yes",
    "[ chitbuzz ]~start with 'r' (rlue)|rule",
    "[ chitbuzz ]~start with 'n' (enwyl)|newly",
    "[ chitbuzz ]~start with 'r' (hcir)|rich",
    "[ chitbuzz ]~start with 'b' (budyd)|buddy",
    "[ chitbuzz ]~start with 'p' (layp)|play",
    "[ chitbuzz ]~start with 's' (tsvoe)|stove",
    "[ chitbuzz ]~7 5 ? 13 11 22 25|10",
    "[ chitbuzz ]~start with 't' (detri)|tired",
    "[ chitbuzz ]~start with 'a' (anegr)|anger",
    "[ chitbuzz ]~start with 'e' (hater)|earth",
    "[ chitbuzz ]~start with 's' (keats)|stake",
    "[ chitbuzz ]~start with 'd' (wdon)|down",
    "[ chitbuzz ]~start with 's' (sac)|sac",
    "[ chitbuzz ]~start with 'b' (labl)|ball",
    "[ chitbuzz ]~start with 'b' (burn)|burn",
    "[ chitbuzz ]~start with 'd' (odor)|door",
    "[ chitbuzz ]~start with 's' (soher)|shore",
    "[ chitbuzz ]~6 18 ? 74 222 888 890 2670 10680 10682|72",
    "[ chitbuzz ]~start with 'o' (ore)|ore",
    "[ chitbuzz ]~start with 'f' (fox)|fox",
    "[ chitbuzz ]~start with 'm' (most)|most",
    "[ chitbuzz ]~start with 'r' (ksir)|risk",
    "math~8 / ? = 1|8",
    "[ chitbuzz ]~start with 'w' (hwsa)|wash",
    "[ chitbuzz ]~start with 'l' (eflt)|left",
    "[ chitbuzz ]~start with 'e' (eletc)|elect",
    "[ chitbuzz ]~start with 'e' (acnet)|enact",
    "[ chitbuzz ]~start with 'o' (roucc)|occur",
    "[ chitbuzz ]~5 2 2 ? 1 1 3 0 0 2|4",
    "[ chitbuzz ]~start with 'w' (wdei)|wide",
    "[ chitbuzz ]~start with 'w' (eawk)|weak",
    "[ chitbuzz ]~start with 'g' (otg)|got",
    "[ chitbuzz ]~start with 'f' (fvaro)|favor",
    "math~6 x ? = 30|5",
    "math~9 - 3 - 2 = ?|4",
    "[ chitbuzz ]~6 9 8 16 ? 18 36|19",
    "[ chitbuzz ]~start with 'l' (lens)|lens",
    "[ chitbuzz ]~start with 't' (wnto)|town",
    "math~3 - 2 = ?|1",
    "[ chitbuzz ]~0 0 3 -1 -3 ? -4 -12 -9 -13|0",
    "[ chitbuzz ]~start with 'a' (doapt)|adopt",
    "[ chitbuzz ]~start with 'h' (ahnd)|hand",
    "[ chitbuzz ]~start with 'g' (goat)|goat",
    "[ chitbuzz ]~start with 'g' (gtif)|gift",
    "[ chitbuzz ]~start with 's' (edse)|seed",
    "math~3 - 3 = ?|0",
    "[ chitbuzz ]~9 10 13 ? 40 43 129|39",
    "[ chitbuzz ]~start with 'b' (cbkri)|brick",
    "[ chitbuzz ]~start with 'm' (map)|map",
    "[ chitbuzz ]~start with 'o' (oen)|one",
    "[ chitbuzz ]~3 ? -3 1 -1 -5 -1 -3 -7 -3|1",
    "[ chitbuzz ]~start with 'l' (mlap)|lamp",
    "[ chitbuzz ]~start with 'a' (unat)|aunt",
    "[ chitbuzz ]~0 0 1 0 0 1 ?|0",
    "[ chitbuzz ]~start with 'f' (aemfr)|frame",
    "[ chitbuzz ]~start with 'h' (rhad)|hard",
    "[ chitbuzz ]~start with 's' (emas)|same",
    "[ chitbuzz ]~start with 'b' (ndeb)|bend",
    "math~8 - ? - 1 = 5|2",
    "[ chitbuzz ]~start with 't' (atitr)|trait",
    "[ chitbuzz ]~start with 'p' (pool)|pool",
    "[ chitbuzz ]~start with 'l' (acle)|lace",
    "[ chitbuzz ]~start with 'd' (rdaw)|draw",
    "math~9 x 3 = ?|27",
    "[ chitbuzz ]~start with 'c' (nocr)|corn",
    "[ chitbuzz ]~start with 'f' (fomr)|form",
    "[ chitbuzz ]~start with 'y' (erya)|year",
    "[ chitbuzz ]~start with 'j' (ourrj)|juror",
    "[ chitbuzz ]~5 9 ? 7 11 9 9|7",
    "[ chitbuzz ]~start with 'e' (end)|end",
    "[ chitbuzz ]~start with 'h' (uhor)|hour",
    "[ chitbuzz ]~start with 'b' (beef)|beef",
    "[ chitbuzz ]~start with 'f' (toof)|foot",
    "[ chitbuzz ]~start with 'h' (ahde)|head",
    "[ chitbuzz ]~start with 'r' (husr)|rush",
    "[ chitbuzz ]~start with 'l' (olok)|look",
    "[ chitbuzz ]~start with 't' (keta)|take",
    "[ chitbuzz ]~start with 'm' (ms)|ms",
    "[ chitbuzz ]~start with 's' (slel)|sell",
    "[ chitbuzz ]~start with 'i' (onri)|iron",
    "[ chitbuzz ]~start with 't' (mtrou)|tumor",
    "[ chitbuzz ]~start with 'd' (dead)|dead",
    "[ chitbuzz ]~start with 'o' (noly)|only",
    "math~8x1=?|8",
    "[ chitbuzz ]~start with 'p' (ipn)|pin",
    "[ chitbuzz ]~start with 'p' (ptar)|part",
    "[ chitbuzz ]~start with 'h' (tahe)|hate",
    "[ chitbuzz ]~start with 'p' (npi)|pin",
    "[ chitbuzz ]~start with 't' (pat)|tap",
    "[ chitbuzz ]~start with 'c' (iclng)|cling",
    "[ chitbuzz ]~start with 'w' (rediw)|weird",
    "[ chitbuzz ]~start with 'e' (entyr)|entry",
    "[ chitbuzz ]~start with 'f' (dofl)|fold",
    "[ chitbuzz ]~start with 'e' (egear)|eager",
    "[ chitbuzz ]~start with 'b' (setb)|best",
    "[ chitbuzz ]~start with 'b' (lebl)|bell",
    "[ chitbuzz ]~6 5 3 5 4 2 4 3 ? 3|1",
    "[ chitbuzz ]~start with 's' (kesa)|sake",
    "[ chitbuzz ]~3 7 9 18 ? 24 48 52 54 108|22",
    "[ chitbuzz ]~start with 'a' (kas)|ask",
    "[ chitbuzz ]~start with 'f' (elshf)|flesh",
    "MATH~2 + ? = 3|1",
    "[ chitbuzz ]~start with 'f' (fra)|far",
    "[ chitbuzz ]~start with 'g' (nagg)|gang",
    "[ chitbuzz ]~start with 'a' (nlago)|along",
    "[ chitbuzz ]~start with 's' (lilsy)|silly",
    "[ chitbuzz ]~start with 'd' (rdop)|drop",
    "[ chitbuzz ]~start with 'r' (aerd)|read",
    "[ chitbuzz ]~start with 'u' (etusp)|upset",
    "[ chitbuzz ]~start with 'a' (ash)|ash",
    "[ chitbuzz ]~start with 's' (sexy)|sexy",
    "[ chitbuzz ]~start with 'b' (adbn)|band",
    "[ chitbuzz ]~start with 'i' (cie)|ice",
    "[ chitbuzz ]~start with 'm' (vome)|move",
    "[ chitbuzz ]~start with 'm' (mind)|mind",
    "[ chitbuzz ]~start with 'm' (etlm)|melt",
    "[ chitbuzz ]~start with 'b' (beak)|bake",
    "[ chitbuzz ]~start with 'd' (od)|do",
    "[ chitbuzz ]~start with 'd' (ydut)|duty",
    "[ chitbuzz ]~start with 'b' (obth)|both",
    "[ chitbuzz ]~start with 's' (aesm)|same",
    "[ chitbuzz ]~start with 'b' (ablyd)|badly",
    "[ chitbuzz ]~start with 'h' (heol)|hole",
    "[ chitbuzz ]~start with 'a' (anut)|aunt",
    "[ chitbuzz ]~start with 'o' (nacoe)|ocean",
    "[ chitbuzz ]~start with 't' (titel)|title",
    "[ chitbuzz ]~start with 'p' (ryap)|pray",
    "[ chitbuzz ]~start with 'z' (zoo)|zoo",
    "MATH~? - 2 - 2 = 4|8",
    "MATH~8 / ? = 4|2",
    "[ chitbuzz ]~start with 's' (tusff)|stuff",
    "[ chitbuzz ]~1 0 0 4 ? 9 13|3",
    "[ chitbuzz ]~start with 's' (asmhs)|smash",
    "[ chitbuzz ]~start with 'p' (epn)|pen",
    "[ chitbuzz ]~start with 'l' (milti)|limit",
    "[ chitbuzz ]~start with 'w' (rowd)|word",
    "[ chitbuzz ]~start with 'e' (seays)|essay",
    "[ chitbuzz ]~2 6 ? 2 6 5 2 6 5 2|5",
    "[ chitbuzz ]~start with 'r' (irse)|rise",
    "[ chitbuzz ]~? 3 4 2 2 3 1|3",
    "[ chitbuzz ]~start with 'b' (bsu)|bus",
    "[ chitbuzz ]~6 10 30 30 34 ? 102|102",
    "math~19-7=?|12",
    "[ chitbuzz ]~start with 'f' (nfid)|find",
    "[ chitbuzz ]~1 2 5 ? 8 11 10|4",
    "[ chitbuzz ]~start with 'h' (dolh)|hold",
    "[ chitbuzz ]~start with 'm' (my)|my",
    "[ chitbuzz ]~start with 'b' (beer)|beer",
    "[ chitbuzz ]~start with 's' (sehll)|shell",
    "[ chitbuzz ]~start with 'b' (obmb)|bomb",
    "[ chitbuzz ]~start with 'b' (enbt)|bent",
    "[ chitbuzz ]~start with 'p' (etaps)|paste",
    "[ chitbuzz ]~start with 'w' (pwar)|wrap",
    "[ chitbuzz ]~start with 'h' (hnoor)|honor",
    "MATH~4 x ? = 12|3",
    "[ chitbuzz ]~start with 's' (fsot)|soft",
    "[ chitbuzz ]~start with 's' (still)|still",
    "[ chitbuzz ]~start with 'w' (hwen)|when",
    "[ chitbuzz ]~start with 'f' (fere)|free",
    "[ chitbuzz ]~start with 'l' (dluo)|loud",
    "[ chitbuzz ]~start with 'm' (rryam)|marry",
    "[ chitbuzz ]~start with 'p' (pruse)|purse",
    "[ chitbuzz ]~start with 'c' (coat)|coat",
    "[ chitbuzz ]~6 12 14 ? 20 22 18 36 38 34|10",
    "[ chitbuzz ]~start with 'l' (slti)|list",
    "[ chitbuzz ]~start with 'w' (rwom)|worm",
    "[ chitbuzz ]~start with 'h' (hhu)|huh",
    "[ chitbuzz ]~start with 'w' (wild)|wild",
    "[ chitbuzz ]~start with 'w' (wyh)|why",
    "[ chitbuzz ]~start with 'c' (eack)|cake",
    "[ chitbuzz ]~8 8 ? 7 7 8 6 6 7 5|9",
    "[ chitbuzz ]~start with 'l' (lnki)|link",
    "[ chitbuzz ]~3 6 ? 4 8 10 6|8",
    "[ chitbuzz ]~start with 'w' (wte)|wet",
    "[ chitbuzz ]~start with 'h' (aht)|hat",
    "[ chitbuzz ]~start with 'o' (aok)|oak",
    "[ chitbuzz ]~start with 'b' (bee)|bee",
    "[ chitbuzz ]~start with 'n' (ingth)|night",
    "[ chitbuzz ]~start with 'm' (emnu)|menu",
    "[ chitbuzz ]~start with 'c' (mlcai)|claim",
    "[ chitbuzz ]~0 0 2 0 0 2 ?|0",
    "[ chitbuzz ]~start with 's' (hsed)|shed",
    "[ chitbuzz ]~start with 't' (ot)|to",
    "[ chitbuzz ]~start with 'e' (seta)|east",
    "[ chitbuzz ]~start with 'f' (efca)|face",
    "[ chitbuzz ]~start with 'r' (erdya)|ready",
    "[ chitbuzz ]~start with 'm' (mcuh)|much",
    "[ chitbuzz ]~7 8 6 8 9 ? 9 10 8 10|7",
    "[ chitbuzz ]~start with 'h' (ohres)|horse",
    "[ chitbuzz ]~4 16 18 17 ? 70 69|68",
    "MATH~7 x 5 = ?|35",
    "[ chitbuzz ]~start with 'p' (ypla)|play",
    "[ chitbuzz ]~start with 's' (ptso)|stop",
    "[ chitbuzz ]~start with 'p' (peace)|peace",
    "[ chitbuzz ]~start with 'p' (aepk)|peak",
    "[ chitbuzz ]~start with 'b' (bkei)|bike",
    "[ chitbuzz ]~start with 's' (ngos)|song",
    "[ chitbuzz ]~start with 'y' (year)|year",
    "[ chitbuzz ]~start with 'l' (line)|line",
    "[ chitbuzz ]~start with 'i' (nyoir)|irony",
    "[ chitbuzz ]~start with 'l' (olck)|lock",
    "[ chitbuzz ]~6 7 9 ? 19 21 42|18",
    "[ chitbuzz ]~start with 'y' (hyea)|yeah",
    "[ chitbuzz ]~start with 'g' (dog)|god",
    "[ chitbuzz ]~start with 'i' (orin)|iron",
    "[ chitbuzz ]~start with 'a' (ma)|am",
    "[ chitbuzz ]~start with 'b' (rbain)|brain",
    "[ chitbuzz ]~start with 'h' (deih)|hide",
    "[ chitbuzz ]~start with 't' (xtai)|taxi",
    "[ chitbuzz ]~start with 'y' (eyra)|year",
    "[ chitbuzz ]~start with 'a' (pepal)|apple",
    "[ chitbuzz ]~start with 'a' (nad)|and",
    "[ chitbuzz ]~3 6 24 20 40 ? 156 312 1248 1244|160",
    "[ chitbuzz ]~2 6 4 ? 0 -2 -6|0",
    "[ chitbuzz ]~start with 'i' (si)|is",
    "[ chitbuzz ]~5 ? 1 3 0 -1 -3 -6 -7 -21|2",
    "[ chitbuzz ]~start with 'b' (arebk)|brake",
    "[ chitbuzz ]~start with 'a' (lal)|all",
    "[ chitbuzz ]~start with 'h' (ahir)|hair",
    "[ chitbuzz ]~start with 'r' (nrak)|rank",
    "MATH~5 x ? = 25|5",
    "[ chitbuzz ]~8 ? 22 88 91 182 728|11",
    "[ chitbuzz ]~start with 'm' (etmal)|metal",
    "[ chitbuzz ]~start with 'm' (omod)|mood",
    "[ chitbuzz ]~start with 'b' (byab)|baby",
    "[ chitbuzz ]~start with 'b' (abet)|beat",
    "[ chitbuzz ]~start with 'm' (mlet)|melt",
    "MATH~7 / ? = 1|7",
    "[ chitbuzz ]~start with 'd' (ndoro)|donor",
    "[ chitbuzz ]~5 5 10 8 8 16 ?|14",
    "[ chitbuzz ]~start with 'd' (darg)|drag",
    "[ chitbuzz ]~2 4 ? 24 26 30 90|8",
    "[ chitbuzz ]~start with 'p' (apn)|pan",
    "[ chitbuzz ]~start with 'b' (blade)|blade",
    "[ chitbuzz ]~start with 'p' (rpzie)|prize",
    "[ chitbuzz ]~start with 'e' (teacx)|exact",
    "[ chitbuzz ]~start with 'b' (bga)|bag",
    "[ chitbuzz ]~start with 't' (tsso)|toss",
    "[ chitbuzz ]~start with 'h' (uhnt)|hunt",
    "[ chitbuzz ]~start with 'c' (cnyad)|candy",
    "[ chitbuzz ]~start with 'm' (itghm)|might",
    "math~7x2=?|14",
    "[ chitbuzz ]~3 3 6 ? 4 8 6|4",
    "[ chitbuzz ]~start with 'g' (grsap)|grasp",
    "[ chitbuzz ]~7 8 6 12 13 ? 22|11",
    "[ chitbuzz ]~3 6 ? 6 12 15 12 24 27 24|9",
    "[ chitbuzz ]~start with 'a' (arch)|arch",
    "[ chitbuzz ]~start with 'w' (rewa)|wear",
    "[ chitbuzz ]~start with 'c' (cool)|cool",
    "[ chitbuzz ]~start with 't' (eot)|toe",
    "MATH~8 - ? = 6|2",
    "[ chitbuzz ]~start with 'd' (eedp)|deep",
    "[ chitbuzz ]~start with 'd' (zdoen)|dozen",
    "[ chitbuzz ]~start with 'h' (ah)|ha",
    "[ chitbuzz ]~start with 'a' (mar)|arm",
    "[ chitbuzz ]~start with 'n' (tne)|net",
    "[ chitbuzz ]~start with 'c' (cut)|cut",
    "[ chitbuzz ]~start with 'd' (rdaft)|draft",
    "[ chitbuzz ]~start with 's' (ecpsa)|space",
    "[ chitbuzz ]~start with 's' (sfot)|soft",
    "[ chitbuzz ]~start with 'w' (wohm)|whom",
    "[ chitbuzz ]~start with 's' (evas)|save",
    "[ chitbuzz ]~start with 'u' (lguy)|ugly",
    "[ chitbuzz ]~start with 'm' (osmt)|most",
    "[ chitbuzz ]~start with 'c' (emoc)|come",
    "[ chitbuzz ]~start with 'u' (iunt)|unit",
    "[ chitbuzz ]~start with 'g' (ung)|gun",
    "[ chitbuzz ]~start with 'b' (obwl)|bowl",
    "MATH~4 + ? = 12|8",
    "[ chitbuzz ]~start with 'h' (lhaf)|half",
    "[ chitbuzz ]~start with 'y' (yte)|yet",
    "[ chitbuzz ]~start with 's' (trhos)|short",
    "[ chitbuzz ]~2 8 16 14 ? 112 110 440 880 878|56",
    "[ chitbuzz ]~start with 'g' (yga)|gay",
    "[ chitbuzz ]~start with 'm' (mksa)|mask",
    "[ chitbuzz ]~start with 't' (tthgi)|tight",
    "[ chitbuzz ]~start with 'r' (race)|race",
    "[ chitbuzz ]~9 8 8 10 9 9 ?|11",
    "[ chitbuzz ]~1 3 3 2 6 6 5 ? 15 14|15",
    "math~1x4=?|4",
    "[ chitbuzz ]~5 ? 9 6 9 10 7 10 11 8|8",
    "[ chitbuzz ]~start with 'o' (npoe)|open",
    "[ chitbuzz ]~start with 'p' (olpt)|plot",
    "[ chitbuzz ]~start with 'a' (ahs)|ash",
    "[ chitbuzz ]~start with 'w' (wdluo)|would",
    "[ chitbuzz ]~start with 'j' (sujt)|just",
    "[ chitbuzz ]~start with 'p' (rpo)|pro",
    "MATH~3 - ? = 1|2",
    "[ chitbuzz ]~start with 's' (skmoe)|smoke",
    "[ chitbuzz ]~start with 'c' (okcr)|cork",
    "[ chitbuzz ]~6 6 5 3 ? 2 0 0 -1 -3|3",
    "[ chitbuzz ]~start with 'a' (add)|add",
    "[ chitbuzz ]~start with 's' (ehos)|shoe",
    "[ chitbuzz ]~start with 'o' (ntoo)|onto",
    "[ chitbuzz ]~start with 'b' (ybu)|buy",
    "[ chitbuzz ]~start with 'h' (raeh)|hear",
    "[ chitbuzz ]~start with 'f' (loof)|fool",
    "[ chitbuzz ]~start with 't' (oty)|toy",
    "[ chitbuzz ]~start with 'p' (pakr)|park",
    "[ chitbuzz ]~start with 'n' (mane)|name",
    "[ chitbuzz ]~start with 'o' (odd)|odd",
    "[ chitbuzz ]~start with 'm' (omno)|moon",
    "[ chitbuzz ]~start with 'a' (ira)|air",
    "[ chitbuzz ]~start with 'd' (kndru)|drunk",
    "[ chitbuzz ]~5 15 19 21 63 67 69 ? 211 213|207",
    "MATH~? x 9 = 45|5",
    "[ chitbuzz ]~start with 'f' (frhot)|forth",
    "[ chitbuzz ]~start with 'o' (ocne)|once",
    "[ chitbuzz ]~start with 'l' (klin)|link",
    "[ chitbuzz ]~start with 'p' (otilp)|pilot",
    "[ chitbuzz ]~8 8 16 14 14 ? 26|28",
    "[ chitbuzz ]~start with 'h' (tohs)|host",
    "[ chitbuzz ]~start with 'r' (anir)|rain",
    "[ chitbuzz ]~start with 'c' (kcae)|cake",
    "[ chitbuzz ]~start with 'b' (bodl)|bold",
    "[ chitbuzz ]~start with 's' (osyrr)|sorry",
    "MATH~5 + 8 = ?|13",
    "[ chitbuzz ]~4 5 8 24 25 28 84 ? 88 264|85",
    "[ chitbuzz ]~start with 'h' (hre)|her",
    "[ chitbuzz ]~start with 'd' (idary)|diary",
    "MATH~2 - 2 x ? = 0|5",
    "[ chitbuzz ]~start with 'h' (hpel)|help",
    "math~7+14=?|21",
    "[ chitbuzz ]~start with 'd' (deyn)|deny",
    "[ chitbuzz ]~start with 'm' (odmo)|mood",
    "[ chitbuzz ]~start with 'u' (until)|until",
    "[ chitbuzz ]~start with 'o' (oyln)|only",
    "[ chitbuzz ]~start with 'm' (cmuh)|much",
    "[ chitbuzz ]~start with 'b' (albl)|ball",
    "[ chitbuzz ]~start with 'v' (voet)|vote",
    "[ chitbuzz ]~start with 'c' (cfae)|cafe",
    "[ chitbuzz ]~start with 'l' (long)|long",
    "[ chitbuzz ]~start with 'l' (yald)|lady",
    "[ chitbuzz ]~start with 'r' (rset)|rest",
    "[ chitbuzz ]~start with 'd' (eadd)|dead",
    "MATH~1 + ? = 2|1",
    "[ chitbuzz ]~start with 'k' (tnko)|knot",
    "[ chitbuzz ]~start with 's' (aasdl)|salad",
    "[ chitbuzz ]~start with 'r' (orb)|rob",
    "[ chitbuzz ]~start with 's' (setm)|stem",
    "[ chitbuzz ]~? 10 6 5 7 3 2|8",
    "[ chitbuzz ]~4 ? 18 17 68 70 69 276 278 277|16",
    "[ chitbuzz ]~start with 'l' (ilfe)|life",
    "[ chitbuzz ]~start with 'l' (dnla)|land",
    "[ chitbuzz ]~start with 'n' (enci)|nice",
    "[ chitbuzz ]~start with 'b' (htba)|bath",
    "[ chitbuzz ]~start with 'h' (deha)|head",
    "[ chitbuzz ]~start with 's' (ishg)|sigh",
    "[ chitbuzz ]~start with 'e' (yeenm)|enemy",
    "[ chitbuzz ]~start with 'b' (lbet)|belt",
    "[ chitbuzz ]~start with 'h' (aehv)|have",
    "[ chitbuzz ]~start with 's' (hscu)|such",
    "[ chitbuzz ]~start with 'g' (eguss)|guess",
    "[ chitbuzz ]~start with 't' (llit)|till",
    "[ chitbuzz ]~start with 'k' (ikss)|kiss",
    "MATH~9 x 4 = ?|36",
    "[ chitbuzz ]~start with 'h' (hepl)|help",
    "[ chitbuzz ]~start with 'o' (oargn)|organ",
    "[ chitbuzz ]~start with 'r' (rian)|rain",
    "[ chitbuzz ]~start with 'b' (bdoy)|body",
    "[ chitbuzz ]~start with 'l' (dela)|lead",
    "[ chitbuzz ]~start with 's' (sanc)|scan",
    "MATH~? x 4 = 36|9",
    "[ chitbuzz ]~start with 'w' (ewst)|west",
    "[ chitbuzz ]~start with 'u' (tnui)|unit",
    "[ chitbuzz ]~6 9 7 28 ? 29 116|31",
    "[ chitbuzz ]~start with 'f' (tryof)|forty"
]